### PR TITLE
Bug 1768507 Add nondistinct count to distinct_docid query

### PR DESCRIPTION
**Pull request by jklukas**
See https://bugzilla.mozilla.org/show_bug.cgi?id=1768507

This is an alternate approach that would replace
https://github.com/mozilla/bigquery-etl/pull/2953
and avoid adding a new table. This also gives us the benefit of allowing
easy access to duplicate rate in decoded tables.

Checklist for reviewer:

- [ ] Commits should reference a bug or github issue, if relevant (if a bug is referenced, the pull request should include the bug number in the title)
- [ ] If the PR comes from a fork, trigger integration CI tests by running the [Push to upstream workflow](https://github.com/mozilla/bigquery-etl/actions/workflows/push-to-upstream.yml) and provide the `<username>:<branch>` of the fork as parameter. The parameter will also show up
in the logs of the `manual-trigger-required-for-fork` CI task together with more detailed instructions.
- [ ] If adding a new field to a query, ensure that the schema and dependent downstream schemas have been updated

For modifications to schemas in restricted namespaces (see [`CODEOWNERS`](/CODEOWNERS)):
- [ ] Follow the [change control procedure](https://docs.google.com/document/d/1TTJi4ht7NuzX6BPG_KTr6omaZg70cEpxe9xlpfnHj9k/edit#heading=h.ttegrcfy18ck)

### CODE REVIEW

**Comment by jklukas** [comment]
I'm looking for review on the approach here. Will need to update the telemetry query and the live view to match before ready to merge.

**Comment by jklukas** [comment]
No updates were needed for the views. They're `SELECT *`.

**Comment by jklukas** [comment]
This is ready for final review, @scholtzan

**Review by scholtzan — APPROVED** [review]

**Comment by jklukas** [comment]
Ran:

```
bqetl query schema deploy --force monitoring_derived.structured_distinct_docids_v1
bqetl query schema deploy --force --ignore-dryrun-skip monitoring_derived.telemetry_distinct_docids_v1
```

**Pull request merged**
