### PR TITLE
fix(Fenix LTV): Switch source from analysis to DS project

### PR DESCRIPTION
**Pull request by kwindau**
## Description

This PR updates the source for Fenix LTV values from the analysis space to the Data science project.

**Reviewer, please follow [this checklist](https://github.com/mozilla/bigquery-etl/blob/main/.github/reviewer_checklist.md)**

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-6900)

### CODE REVIEW

**Review by whd — COMMENTED** [review]
I would caution against using `moz-fx-data-bq-data-science` in any production capacity. It has the same problems as `analysis` in that the datasets there are not guaranteed to be productionized in any fashion (for instance this dataset appears to be created by loines).  Additionally airflow shouldn't have access to this data (see https://github.com/mozilla-services/cloudops-infra/blob/master/projects/data-bq-teams/tf/global/folder/main.tf), but it appears that it does currently. I need to track down how this occurred but it looks like it was due to somebody applying a terraform change that never got merged.

So my recommendation as someone with no context would be to productionize `android_state_ltvs_v2` in shared-prod directly and use that.

**Comment by whd** [comment]
> Additionally airflow shouldn't have access to this data (see https://github.com/mozilla-services/cloudops-infra/blob/master/projects/data-bq-teams/tf/global/folder/main.tf), but it appears that it does currently.

I tracked this down to https://github.com/mozilla-services/cloudops-infra/pull/6128 which is demonstrating that airflow in fact should not have access to this data. I should though and even I don't see it:

```
$ bq --project_id moz-fx-data-bq-data-science show loines.android_state_ltvs_v2
BigQuery error in show operation: Not found: Table moz-fx-data-bq-data-science:loines.android_state_ltvs_v2
```

So while it's possible for :loines:
```
bq --project_id moz-fx-data-bq-data-science show loines
Dataset moz-fx-data-bq-data-science:loines

   Last modified            ACLs            Labels    Type     Max time travel (Hours)  
 ----------------- ----------------------- -------- --------- ------------------------- 
  17 Apr 09:39:42   Owners:                          DEFAULT   168                      
                      loines@mozilla.com,                                               
                      projectOwners                                                     
                    Writers:                                                            
                      projectWriters                                                    
                    Readers:                                                            
                      projectReaders  
```
as Owner of the dataset to grant airflow access, that access would need to be manually applied and that's discouraged per my previous comment.

**Comment by kwindau** [comment]
Closing for now per @whd 's suggestion - will reach out to @irrationalagent to see if I can get the code used to build these 3 tables and start working on productionalizing them as query.py files with all the python packages/inputs used

- mozdata.analysis.firefox_desktop_state_ltvs_v1 
- mozdata.analysis.ios_state_ltvs_v2
- mozdata.analysis.android_state_ltvs_v2

**Comment by whd** [comment]
https://github.com/mozilla/bigquery-etl/blob/main/sql/moz-fx-data-shared-prod/braze_derived/dataset_metadata.yaml#L8 is an example of a dataset you could make swapping `workgroup:braze/writers` with `workgroup:datascience/developers` to give them a dataset to create tables in that are more accessible to production ETL without needing to go through full production bqetl setup.

**Pull request closed without merging**
