### PR TITLE
Support escaping only project_id in view definition

### LINKED ISSUE #1426: Handle different escaping formats for project IDs in view definitions
we currently only handle ``` `project.dataset.table` ``` format, and we should also correctly handle ``` `project`.dataset.table``` format

### PR DESCRIPTION
**Pull request by relud**
fixes #1426 

verified that this has the intended behavior:
```bash
$ git co master
Switched to branch 'master'
Your branch is up to date with 'origin/master'.
$ script/publish_views --target-project=moz-fx-data-shared-prod --dry-run sql/moz-fx-data-shared-prod/mozilla_vpn/waitlist/view.sql
Validated definition of `moz-fx-data-shared-prod.mozilla_vpn.waitlist` in sql/moz-fx-data-shared-prod/mozilla_vpn/waitlist/view.sql
$ sed 's/`moz-fx-data-shared-prod.mozilla_vpn.waitlist`/`moz-fx-data-shared-prod`.mozilla_vpn.waitlist/' -i sql/moz-fx-data-shared-prod/mozilla_vpn/waitlist/view.sql
$ script/publish_views --target-project=moz-fx-data-shared-prod --dry-run sql/moz-fx-data-shared-prod/mozilla_vpn/waitlist/view.sql
google.api_core.exceptions.BadRequest: 400 POST https://bigquery.googleapis.com/bigquery/v2/projects/relud-17123/jobs: Syntax error: Unclosed identifier literal at [2:3]

(job ID: 2ebe2f77-9556-4a4b-b28a-0e87e588e716)

                -----Query Job SQL Follows-----

    |    .    |    .    |    .    |    .    |    .    |
   1:CREATE OR REPLACE VIEW
   2:  `moz-fx-data-shared-prod.mozilla_vpn.waitlist
   3:AS
   4:SELECT
   5:  *
   6:FROM
   7:  `moz-fx-data-shared-prod`.mozilla_vpn_derived.waitlist_v1
    |    .    |    .    |    .    |    .    |    .    |
$ git co fix-publish-views
M	sql/moz-fx-data-shared-prod/mozilla_vpn/waitlist/view.sql
Switched to branch 'fix-publish-views'
Your branch is up to date with 'origin/fix-publish-views'.
$ script/publish_views --target-project=moz-fx-data-shared-prod --dry-run sql/moz-fx-data-shared-prod/mozilla_vpn/waitlist/view.sql
Validated definition of `moz-fx-data-shared-prod`.mozilla_vpn.waitlist in sql/moz-fx-data-shared-prod/mozilla_vpn/waitlist/view.sql
```

cc @scholtzan

### CODE REVIEW

**Review by fbertsch — CHANGES_REQUESTED** [review]
This replace logic leaves a lot of room for accidents in names: e.g. double-backticks, backticks within project names, etc. It would be prudent to limit the number of errors we allow in that way.

**Comment by fbertsch** [comment]
I'll note that that wouldn't be the case if we remove the target project during dryrun.

**Comment by relud** [comment]
> This replace logic leaves a lot of room for accidents in names: e.g. double-backticks, backticks within project names, etc. It would be prudent to limit the number of errors we allow in that way.

BigQuery does not support triple/double backticks for escaping identifiers. [docs](https://cloud.google.com/bigquery/docs/reference/standard-sql/lexical#identifiers) don't mention multi-backticks and using a triple-backtick or double-backtick results in `Syntax error: Invalid empty identifier` for dry running a query like:

     CREATE OR REPLACE VIEW ```moz-fx-data-shared-prod```.dataset.table AS SELECT 1 AS a

And while it is lexically valid to specify a project name with a backtick in it, that results in ```Invalid project ID 'moz-fx-data-sh`a`red-prod'. Project IDs must contain 6-63 lowercase letters, digits, or dashes. Some project IDs also include domain name separated by a colon. IDs must start with a letter and may not end with a dash.``` for dry running a query like:

    CREATE OR REPLACE VIEW `moz-fx-data-sh\`a\`red-prod`.dataset.table AS SELECT 1 AS a

It's also not allowable to partially-escape an identifier, because that results in `Syntax error: Expected keyword AS but got identifier "prod"` for dry running a query like:

    CREATE OR REPLACE VIEW `moz-fx-data-shared-`prod.dataset.table AS SELECT 1 AS a

So this replace logic should be fine as long as we have a valid view definition that actually contains a project name. (missing project name is a separate matter tracked in #1413)

**Comment by relud** [comment]
> And while it is lexically valid to specify a project name with a backtick in it, that results in `` Invalid project ID 'moz-fx-data-sh`a`red-prod'. Project IDs must contain 6-63 lowercase letters, digits, or dashes. Some project IDs also include domain name separated by a colon. IDs must start with a letter and may not end with a dash. `` for dry running a query like:
> 
> ```
> CREATE OR REPLACE VIEW `moz-fx-data-sh\`a\`red-prod`.dataset.table AS SELECT 1 AS a
> ```

This reveals a different bug where project_ids of the form `{domain_name}:{project_id}` would not be correctly detected, which f112260 fixes by rewriting `.split(".", 1)[0]` as `.rsplit(".", 2)[0]`, so that it splits from the right instead of the left.

**Review by fbertsch — APPROVED** [review]
Gotcha - I misleadingly thought the dryrun was running in `publish_views`, but it's not :) sounds like we don't need to worry about those edge cases.

**Pull request merged**
