### PR TITLE
[RS-834] Add country to search_revenue_levers_daily

### PR DESCRIPTION
**Pull request by skahmann3**
Checklist for reviewer:

- [ ] Commits should reference a bug or github issue, if relevant (if a bug is referenced, the pull request should include the bug number in the title).
- [ ] If the PR comes from a fork, trigger integration CI tests by running the [Push to upstream workflow](https://github.com/mozilla/bigquery-etl/actions/workflows/push-to-upstream.yml) and provide the `<username>:<branch>` of the fork as parameter. The parameter will also show up
in the logs of the `manual-trigger-required-for-fork` CI task together with more detailed instructions.
- [ ] If adding a new field to a query, ensure that the schema and dependent downstream schemas have been updated.
- [ ] When adding a new derived dataset, ensure that data is not available already (fully or partially) and recommend extending an existing dataset in favor of creating new ones. Data can be available in the [bigquery-etl repository](https://github.com/mozilla/bigquery-etl), [looker-hub](https://github.com/mozilla/looker-hub) or in [looker-spoke-default](https://github.com/mozilla/looker-spoke-default/tree/e1315853507fc1ac6e78d252d53dc8df5f5f322b).

For modifications to schemas in restricted namespaces (see [`CODEOWNERS`](https://github.com/mozilla/bigquery-etl/blob/main/CODEOWNERS)):
- [ ] Follow the [change control procedure](https://docs.google.com/document/d/1TTJi4ht7NuzX6BPG_KTr6omaZg70cEpxe9xlpfnHj9k/edit#heading=h.ttegrcfy18ck)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2253)

### CODE REVIEW

**Comment by skahmann3** [comment]
Replaced the US vs ROW column with exact country. This means we'll need to adjust and manually aggregate anything that filters to "ROW." I made this decision so we don't have to maintain any lists of top markets to power a US vs "top 10 ROW" vs "Other ROW" grouping since any grouping decisions will be done in the analysis stage.

**Review by curtismorales — APPROVED** [review]
This looks right to me! Have you tested to see if the results look right?

And how far back are going to need to backfill?

**Comment by skahmann3** [comment]
> This looks right to me! Have you tested to see if the results look right?
> 
> And how far back are going to need to backfill?

I checked the US results against what we currently have in the table. It looks like this table goes back to 2018, so ideally we'd backfill all of it, though if we had to prioritize then 2021+ dates

**Comment by xluo-ds** [comment]
I will review these once I am back in early Jan.

**Comment by xluo-ds** [comment]
PR needs to be updated based on several things,

- [ ] Waiting from Joy to see how we can add `default_search_engine` to the AUA tables to reduce maintenance effort with up coming KPI improvements
- [ ] 2 new countries are added to Google monetization list starting from Dec 1, 2023 which needed to be reflected
- [ ] Preethi's work on adjustment factor for default search engine bug (https://mozilla-hub.atlassian.net/browse/RS-897 )

**Comment by skahmann3** [comment]
> PR needs to be updated based on several things,
> 
>     * [ ]  Waiting from Joy to see how we can add `default_search_engine` to the AUA tables to reduce maintenance effort with upcoming KPI improvements
> 
>     * [ ]  2 new countries are added to Google monetization list starting from Dec 1, 2023 which needed to be reflected
> 
>     * [ ]  Preethi's work on adjustment factor for default search engine bug (https://mozilla-hub.atlassian.net/browse/RS-897 )

For #1 above, we've kicked off a slack channel to resolve adding new things to AUA.

For #2 above, I think we should just add dates to the country filter (e.g. before Dec 2023, remove 6 markets; after Dec 2023, remove 4 markets). Conversely, we could remove the country filter and instead add a column for monetized vs nonmonetized (e.g. we'd need to aggregate using filter monetized = "Y"). I think the first option makes more sense from the user perspective, but let me know if you disagree from a user or implementation standpoint.

**Comment by skahmann3** [comment]
CC @m-d-bowerman since changes to search_revenue_levers_daily will impact the automated forecasts

**Comment by skahmann3** [comment]
@xluo-ds any objections to fixing the channel coding in this table so it matches the revenue table? E.g. "ESR" not "esr" and "n/a" for mobile channel? Or we could always make the mobile channel consistently "personal" to match our forecasts?

**Comment by xluo-ds** [comment]
> @xluo-ds any objections to fixing the channel coding in this table so it matches the revenue table? E.g. "ESR" not "esr" and "n/a" for mobile channel? Or we could always make the mobile channel consistently "personal" to match our forecasts?

Hey @skahmann3 , I am fine with that to be consistent with the search revenue table.

**Review by alekhyamoz — APPROVED** [review]

**Pull request merged**
