### PR TITLE
Use zetasql to get dependencies for dag generation

### PR DESCRIPTION
**Pull request by relud**
~requires #1802~

### CODE REVIEW

**Comment by scholtzan** [comment]
I tried running `./bqetl dag generate bqetl_experiments_daily`, but the following error occurs:

```
INFO:root:Get dependencies for experiment_enrollment_daily_active_population
Traceback (most recent call last):
  File "venv/bin/bqetl", line 33, in <module>
    sys.exit(load_entry_point('mozilla-bigquery-etl', 'console_scripts', 'bqetl')())
  File "/bigquery-etl/bigquery_etl/cli/__init__.py", line 48, in cli
    group(prog_name=prog_name)
  File "/bigquery-etl/venv/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/bigquery-etl/venv/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/bigquery-etl/venv/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/bigquery-etl/venv/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/bigquery-etl/venv/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/bigquery-etl/venv/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/bigquery-etl/bigquery_etl/cli/dag.py", line 186, in generate
    dags.dag_to_airflow(output_dir, dag)
  File "/bigquery-etl/bigquery_etl/query_scheduling/dag_collection.py", line 106, in dag_to_airflow
    dag.to_airflow_dag(self), fast=False, mode=FileMode()
  File "/bigquery-etl/bigquery_etl/query_scheduling/dag.py", line 214, in to_airflow_dag
    task.with_dependencies(dag_collection)
  File "/bigquery-etl/bigquery_etl/query_scheduling/task.py", line 343, in with_dependencies
    for table in self._get_referenced_tables():
  File "/bigquery-etl/bigquery_etl/query_scheduling/task.py", line 328, in _get_referenced_tables
    table_names = {
  File "/bigquery-etl/bigquery_etl/query_scheduling/task.py", line 331, in <setcomp>
    for table in extract_table_references_without_views(query_file)
  File "/bigquery-etl/bigquery_etl/dependency.py", line 59, in extract_table_references_without_views
    for table in extract_table_references(path.read_text()):
  File "/bigquery-etl/bigquery_etl/dependency.py", line 39, in extract_table_references
    options = AnalyzerOptions()
  File "jnius/jnius_export_class.pxi", line 270, in jnius.JavaClass.__init__
  File "jnius/jnius_export_class.pxi", line 370, in jnius.JavaClass.call_constructor
  File "jnius/jnius_jvm_dlopen.pxi", line 91, in jnius.create_jnienv
jnius.JavaException: JVM exception occurred: UNKNOWN com.google.zetasql.io.grpc.StatusRuntimeException
```

**Comment by relud** [comment]
> `jnius.JavaException: JVM exception occurred: UNKNOWN com.google.zetasql.io.grpc.StatusRuntimeException`

I'm having trouble reproducing this exception, could you give some more info about how to reproduce it and the environment it's running in?

**Comment by scholtzan** [comment]
Turns out my `$JAVA_HOME` was pointing to an incorrect path. After fixing it, the error went away and it's working now.

**Review by scholtzan — APPROVED** [review]
This is definitely a good improvement.

One thing I'm a little concerned about is that setting up/installing the CLI is a little more effort. Users will need to install a JDK and Maven. We should probably document these requirements somewhere.

**Comment by relud** [comment]
> One thing I'm a little concerned about is that setting up/installing the CLI is a little more effort. Users will need to install a JDK and Maven. We should probably document these requirements somewhere.

r? 23e31264

**Review by scholtzan — APPROVED** [review]
👍

**Pull request merged**
