### PR TITLE
Add Suggestion fields to aggregated_search_terms_daily

### PR DESCRIPTION
**Pull request by rebecca-burwei**
Search-term-level analysis is not useful to the business. They want to see things like "how many clicks do we get on ebay watches?" or "how many clicks do we get in shopping (iab_category)?". 

I'm proposing to add these additional fields to aggregated_search_terms_daily. It's possible this PR is rejoining on fields that were previously dropped further up the sanitization pipeline (not sure - got a tip from Alessio that this might be the case).

Checklist for reviewer:

- [ ] Commits should reference a bug or github issue, if relevant (if a bug is referenced, the pull request should include the bug number in the title)
- [ ] If the PR comes from a fork, trigger integration CI tests by running the [Push to upstream workflow](https://github.com/mozilla/bigquery-etl/actions/workflows/push-to-upstream.yml) and provide the `<username>:<branch>` of the fork as parameter. The parameter will also show up
in the logs of the `manual-trigger-required-for-fork` CI task together with more detailed instructions.
- [ ] If adding a new field to a query, ensure that the schema and dependent downstream schemas have been updated

For modifications to schemas in restricted namespaces (see [`CODEOWNERS`](/CODEOWNERS)):
- [ ] Follow the [change control procedure](https://docs.google.com/document/d/1TTJi4ht7NuzX6BPG_KTr6omaZg70cEpxe9xlpfnHj9k/edit#heading=h.ttegrcfy18ck)

### CODE REVIEW

**Review by whd — COMMENTED** [review]
@rebecca-burwei I just merged https://github.com/mozilla/bigquery-etl/pull/3017 which should hopefully fix the test if you rebase this, but this PR also looks like the SQL needs to be formatted.

**Review by jklukas — CHANGES_REQUESTED** [review]
I don't think we're currently set up to accept the new fields in the table, so I expect this job will error out if merged as is.

We can add the following to the `scheduling` section in `metadata.yaml`:

```
   arguments: ['--schema_update_option=ALLOW_FIELD_ADDITION']
```

Or we could do this join in the user-facing view rather than in this query directly.

Otherwise, we'd need to define a `schema.yaml` and deploy that.

**Comment by jklukas** [comment]
I think I'm going to go ahead and push a change here to add ALLOW_FIELD_ADDITION.

**Review by jklukas — APPROVED** [review]
I pushed the scheduling config update. This should be good to go once CI passes.

**Pull request merged**
