### PR TITLE
Fix google sheets metadata and change from "google_sheet" to "google_sheets" for consistency with google

### PR DESCRIPTION
**Pull request by curtismorales**
The airflow table deployment has been failing for some tables with the following error
https://workflow.telemetry.mozilla.org/log?dag_id=bqetl_artifact_deployment&task_id=publish_new_tables&execution_date=2023-06-06T05%3A30%3A00%2B00%3A00

Upon investigating we found that a recent PR #3881 has change the way we parse the metadata for external config for google sheets. We have been using `"GOOGLE_SHEET"/"google_sheet"` in our config while google uses "GOOGLE_SHEETS." Previously we were doing the translation and #3881 changed to do it differently.

We could bring that translation back, but we thought it made more sense to bring our terminology in line with Google's.

We have a matching PR in `private-bigquery-etl` to accommodate this change https://github.com/mozilla/private-bigquery-etl/pull/234

Checklist for reviewer:

- [ ] Commits should reference a bug or github issue, if relevant (if a bug is referenced, the pull request should include the bug number in the title).
- [ ] If the PR comes from a fork, trigger integration CI tests by running the [Push to upstream workflow](https://github.com/mozilla/bigquery-etl/actions/workflows/push-to-upstream.yml) and provide the `<username>:<branch>` of the fork as parameter. The parameter will also show up
in the logs of the `manual-trigger-required-for-fork` CI task together with more detailed instructions.
- [ ] If adding a new field to a query, ensure that the schema and dependent downstream schemas have been updated.
- [ ] When adding a new derived dataset, ensure that data is not available already (fully or partially) and recommend extending an existing dataset in favor of creating new ones. Data can be available in the [bigquery-etl repository](https://github.com/mozilla/bigquery-etl), [looker-hub](https://github.com/mozilla/looker-hub) or in [looker-spoke-default](https://github.com/mozilla/looker-spoke-default/tree/e1315853507fc1ac6e78d252d53dc8df5f5f322b).

For modifications to schemas in restricted namespaces (see [`CODEOWNERS`](https://github.com/mozilla/bigquery-etl/blob/main/CODEOWNERS)):
- [ ] Follow the [change control procedure](https://docs.google.com/document/d/1TTJi4ht7NuzX6BPG_KTr6omaZg70cEpxe9xlpfnHj9k/edit#heading=h.ttegrcfy18ck)

### CODE REVIEW

**Comment by curtismorales** [comment]
This seemed like the better change but it did require editing the metadata for several existing tables. I'm hoping that artifact deployment won't feel the need to rebuild these tables, but I'm not totally sure

**Comment by whd** [comment]
This metadata format is used in ops logic at https://github.com/mozilla-services/cloudops-infra/blob/master/projects/data-shared/tf/modules/derived-acls/sheets.tf#L3 so a corresponding PR needs to be filed to change that value to avoid breaking some ACL deployment logic.

**Review by scholtzan — APPROVED** [review]
Good to be consistent! Thanks!

**Comment by scholtzan** [comment]
I think there are also some tables in private-bigquery-etl that use this and would need to be updated

**Comment by curtismorales** [comment]
> This metadata format is used in ops logic at https://github.com/mozilla-services/cloudops-infra/blob/master/projects/data-shared/tf/modules/derived-acls/sheets.tf#L3 so a corresponding PR needs to be filed to change that value to avoid breaking some ACL deployment logic.

Thanks, I'll take a look

**Comment by curtismorales** [comment]
> I think there are also some tables in private-bigquery-etl that use this and would need to be updated

Alekhya has a PR ready! https://github.com/mozilla/private-bigquery-etl/pull/234

**Comment by alekhyamoz** [comment]
@whd  here is a PR for your review - https://github.com/mozilla-services/cloudops-infra/pull/4921

**Pull request merged**
