### PR TITLE
Add experiments field from clients_daily to urlbar_clients_daily

### PR DESCRIPTION
**Pull request by rebecca-burwei**
Checklist for reviewer:

- [ ] Commits should reference a bug or github issue, if relevant (if a bug is referenced, the pull request should include the bug number in the title)
- [ ] If the PR comes from a fork, trigger integration CI tests by running the [Push to upstream workflow](https://github.com/mozilla/bigquery-etl/actions/workflows/push-to-upstream.yml) and provide the `<username>:<branch>` of the fork as parameter. The parameter will also show up
in the logs of the `manual-trigger-required-for-fork` CI task together with more detailed instructions.
- [ ] If adding a new field to a query, ensure that the schema and dependent downstream schemas have been updated

For modifications to schemas in restricted namespaces (see [`CODEOWNERS`](/CODEOWNERS)):
- [ ] Follow the [change control procedure](https://docs.google.com/document/d/1TTJi4ht7NuzX6BPG_KTr6omaZg70cEpxe9xlpfnHj9k/edit#heading=h.ttegrcfy18ck)

### CODE REVIEW

**Comment by rebecca-burwei** [comment]
If this PR is merged, will [this Looker file](https://github.com/mozilla/looker-hub/blob/main/awesome_bar/views/urlbar_clients_daily.view.lkml) automatically get updated?

**Comment by ANich** [comment]
> If this PR is merged, will [this Looker file](https://github.com/mozilla/looker-hub/blob/main/awesome_bar/views/urlbar_clients_daily.view.lkml) automatically get updated?

Yup, once we update the schema. Should this be backfilled @rebecca-burwei?

**Comment by rebecca-burwei** [comment]
> Should this be backfilled @rebecca-burwei?

@ANich yes, are there changes I can add to the PR to help facilitate the backfill?

**Comment by ANich** [comment]
> > Should this be backfilled @rebecca-burwei?
> 
> @ANich yes, are there changes I can add to the PR to help facilitate the backfill?

Yup, the steps are here: https://mozilla.github.io/bigquery-etl/cookbooks/common_workflows/#add-a-new-field-to-clients_daily 

So the remaining steps are to run `/bqetl query schema update telemetry_derived.urlbar_clients_daily_v1 --update_downstream` to update the `schema.yaml` 

I'll review. Then once it's merged you (or I) can deploy the schema by running `/bqetl query schema deploy telemetry_derived.urlbar_clients_daily_v1`

**Comment by jklukas** [comment]
> Then once it's merged you (or I) can deploy the schema by running /bqetl query schema deploy telemetry_derived.urlbar_clients_daily_v1

IIRC, only data eng has write access to `_derived` datasets, so the deploy and backfill steps will require DE involvement.

**Review by ANich — APPROVED** [review]

**Comment by ANich** [comment]
> @ANich yes, are there changes I can add to the PR to help facilitate the backfill?

Should I backfill from the beginning of this table or did you have a particular date in mind?

**Comment by rebecca-burwei** [comment]
> Should I backfill from the beginning of this table or did you have a particular date in mind?

Backfilling from the beginning of the table would be better, but if there is some cost limitation, then backfilling from Sept 1, 2021 onwards would be okay.

**Comment by ANich** [comment]
This is backfilled 👍

**Pull request merged**
