### PR TITLE
Add new table with changed column names

### PR DESCRIPTION
**Pull request by chelseatroy**
Apropos of [this ticket](https://mozilla-hub.atlassian.net/browse/DENG-205). 

@quiiver and I agreed that the least disruptive way to do this is to create a new table, manually copy over the data from the old table once we know the new table is working, and then remove the old table.

Checklist for reviewer:

- [x] Commits should reference a bug or github issue, if relevant (if a bug is referenced, the pull request should include the bug number in the title)
- [x] If the PR comes from a fork, trigger integration CI tests by running the [Push to upstream workflow](https://github.com/mozilla/bigquery-etl/actions/workflows/push-to-upstream.yml) and provide the `<username>:<branch>` of the fork as parameter. The parameter will also show up
in the logs of the `manual-trigger-required-for-fork` CI task together with more detailed instructions.
- [x] If adding a new field to a query, ensure that the schema and dependent downstream schemas have been updated

For modifications to schemas in restricted namespaces (see [`CODEOWNERS`](/CODEOWNERS)):
- [x] Follow the [change control procedure](https://docs.google.com/document/d/1TTJi4ht7NuzX6BPG_KTr6omaZg70cEpxe9xlpfnHj9k/edit#heading=h.ttegrcfy18ck)

### CODE REVIEW

**Review by quiiver — APPROVED** [review]
lgtm would be good to get @rebecca-burwei eyes on this as well

**Comment by quiiver** [comment]
forgot that Rebecca is out this week at scipy. no need to block on that

**Comment by cmharlow** [comment]
no review required from jbuck; we do need one from jason bc of the change control procedures involved with this particular set of changes. i'm working with him now to get this okay-ed & appropriately documented for SRE purposes.

**Comment by cmharlow** [comment]
Given mine & @jasonthomas reading of the change control procedures and the changes here / discussion in the linked DENG ticket, I'm making a change control ticket for @mreid-moz 's approval just to be safe. https://mozilla-hub.atlassian.net/browse/DSRE-899

Once that's in, @jasonthomas (as a code owner) will approve and i'll merge / work on deploy.

**Comment by chelseatroy** [comment]
Thank you @cmharlow!! 🥳

**Review by jasonthomas — APPROVED** [review]

**Pull request merged**
