### PR TITLE
Feature: 'repo/bigquery-etl' tag added automatically during DAG generation.

### PR DESCRIPTION
**Pull request by kik-kik**
Checklist for reviewer:

- [ ] Commits should reference a bug or github issue, if relevant (if a bug is referenced, the pull request should include the bug number in the title)
- [ ] If the PR comes from a fork, trigger integration CI tests by running the [Push to upstream workflow](https://github.com/mozilla/bigquery-etl/actions/workflows/push-to-upstream.yml) and provide the `<username>:<branch>` of the fork as parameter. The parameter will also show up
in the logs of the `manual-trigger-required-for-fork` CI task together with more detailed instructions.
- [ ] If adding a new field to a query, ensure that the schema and dependent downstream schemas have been updated

For modifications to schemas in restricted namespaces (see [`CODEOWNERS`](/CODEOWNERS)):
- [ ] Follow the [change control procedure](https://docs.google.com/document/d/1TTJi4ht7NuzX6BPG_KTr6omaZg70cEpxe9xlpfnHj9k/edit#heading=h.ttegrcfy18ck)

### CODE REVIEW

**Comment by kik-kik** [comment]
I did not regenerate DAGs yet just to make it easier to see the actual changes I am proposing

**Review by scholtzan — APPROVED** [review]
looks good to me

**Review by jklukas — APPROVED** [review]

**Comment by kik-kik** [comment]
I assume it's good for me to merge or should I wait until after the code freeze? @scholtzan @jklukas ?

**Comment by scholtzan** [comment]
Should be fine to merge after you have generated the DAGs.

**Pull request merged**
