### PR TITLE
Create dataset for Greenhouse derived tables

### PR DESCRIPTION
**Pull request by sbrownmoz**
Creating a dataset to hold Greenhouse derived tables for Looker (People).

Checklist for reviewer:

- [ ] Commits should reference a bug or github issue, if relevant (if a bug is referenced, the pull request should include the bug number in the title).
- [ ] If the PR comes from a fork, trigger integration CI tests by running the [Push to upstream workflow](https://github.com/mozilla/bigquery-etl/actions/workflows/push-to-upstream.yml) and provide the `<username>:<branch>` of the fork as parameter. The parameter will also show up
in the logs of the `manual-trigger-required-for-fork` CI task together with more detailed instructions.
- [ ] If adding a new field to a query, ensure that the schema and dependent downstream schemas have been updated.
- [ ] When adding a new derived dataset, ensure that data is not available already (fully or partially) and recommend extending an existing dataset in favor of creating new ones. Data can be available in the [bigquery-etl repository](https://github.com/mozilla/bigquery-etl), [looker-hub](https://github.com/mozilla/looker-hub) or in [looker-spoke-default](https://github.com/mozilla/looker-spoke-default/tree/e1315853507fc1ac6e78d252d53dc8df5f5f322b).

For modifications to schemas in restricted namespaces (see [`CODEOWNERS`](https://github.com/mozilla/bigquery-etl/blob/main/CODEOWNERS)):
- [ ] Follow the [change control procedure](https://docs.google.com/document/d/1TTJi4ht7NuzX6BPG_KTr6omaZg70cEpxe9xlpfnHj9k/edit#heading=h.ttegrcfy18ck)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1666)

### CODE REVIEW

**Comment by whd** [comment]
People team data is generally managed separately from bigquery-etl, see https://mozilla-hub.atlassian.net/browse/DSRE-330 for details. If you need a dataset provisioned in that project filing a DSRE ticket is probably the correct avenue for that.

**Comment by sbrownmoz** [comment]
We were looking to utilize the bqetl tool to create our derived tables in
moz-fx-data-bq-people.  Anna Scholtz. advised us that this was possible.
Is that incorrect?

**Comment by whd** [comment]
> We were looking to utilize the bqetl tool to create our derived tables in
> moz-fx-data-bq-people.  Anna Scholtz advised us that this was possible.
> Is that incorrect?

That is AIUI incorrect. The original intent in https://mozilla-hub.atlassian.net/browse/DSRE-330 was to grant Airflow management access to this project, and that is how it was originally implemented. However, after https://mozilla-hub.atlassian.net/browse/DSRE-383 landed we explicitly removed Airflow's access to the project as requested.

So there are two things that would need to be changed to make this work:

1. Remove `dataset_metadata.yaml` from this PR, and instead provision that dataset via cloudops-infra
https://github.com/mozilla/bigquery-etl/pull/4213#discussion_r1321894363 contains some discussion about support for this file. We could consider supporting the metadata in non-shared-prod/mozdata projects but that's out of scope for the current proposed changes. It's unlikely `workgroup:mozilla-confidential` is the appropriate grant for the dataset at any rate.
2. Re-grant Airflow the requisite access to populate tables in datasets created in the people project

/CC @scholtzan, I imagine opening up Airflow access to people data is worth reviewing with management.

**Comment by scholtzan** [comment]
I'll bring up the Airflow access to people data with management tomorrow. 

I guess we might need a new workgroup which determines who can access this data. Adding this information to a ticket in https://mozilla-hub.atlassian.net/jira/software/c/projects/DSRE/issues would be helpful.

In any case, we'll probably want to have the queries related to people data in our private repo: https://github.com/mozilla/private-bigquery-etl

**Comment by whd** [comment]
> I guess we might need a new workgroup which determines who can access this data.

I hope `workgroup:people` suffices, although the [executive sponsor](https://github.com/mozilla-services/cloudops-infra/tree/master/projects/data-shared/tf/global/access-groups/people) probably needs to be updated.

**Comment by sbrownmoz** [comment]
Thanks for the clarification.  I will submit tickets for the new datasets needed to hold the derived tables.  What do I need to do initiate the re-granting of Airflow access in the people project?  And just to be clear, once Airflow access is granted, will we be able to use the bqetl tool to create our derived tables?

Also, should we just close this pull request since it sounds like our queries will need to be in the private repository?

**Comment by whd** [comment]
> What do I need to do initiate the re-granting of Airflow access in the people project? 

As part of the request for the dataset you can add that Airflow needs write access to the dataset, and the rest can be sorted out in the Jira ticket.

> And just to be clear, once Airflow access is granted, will we be able to use the bqetl tool to create our derived tables?

Yes.

> Also, should we just close this pull request since it sounds like our queries will need to be in the private repository?

Yes. I'll close this.

**Pull request closed without merging**
