### PR TITLE
[RS-744] Add search with ads, monetizable sap, and organic search/ ad clicks/ search with ads

### PR DESCRIPTION
**Pull request by skahmann3**
Checklist for reviewer:

- [ ] Commits should reference a bug or github issue, if relevant (if a bug is referenced, the pull request should include the bug number in the title).
- [ ] If the PR comes from a fork, trigger integration CI tests by running the [Push to upstream workflow](https://github.com/mozilla/bigquery-etl/actions/workflows/push-to-upstream.yml) and provide the `<username>:<branch>` of the fork as parameter. The parameter will also show up
in the logs of the `manual-trigger-required-for-fork` CI task together with more detailed instructions.
- [ ] If adding a new field to a query, ensure that the schema and dependent downstream schemas have been updated.
- [ ] When adding a new derived dataset, ensure that data is not available already (fully or partially) and recommend extending an existing dataset in favor of creating new ones. Data can be available in the [bigquery-etl repository](https://github.com/mozilla/bigquery-etl), [looker-hub](https://github.com/mozilla/looker-hub) or in [looker-spoke-default](https://github.com/mozilla/looker-spoke-default/tree/e1315853507fc1ac6e78d252d53dc8df5f5f322b).

For modifications to schemas in restricted namespaces (see [`CODEOWNERS`](https://github.com/mozilla/bigquery-etl/blob/main/CODEOWNERS)):
- [ ] Follow the [change control procedure](https://docs.google.com/document/d/1TTJi4ht7NuzX6BPG_KTr6omaZg70cEpxe9xlpfnHj9k/edit#heading=h.ttegrcfy18ck)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1076)

### CODE REVIEW

**Comment by skahmann3** [comment]
@curtismorales and @alekhyamoz - Can one of you help me get this merged and backfilled by end of next week? I know Curtis is going to be out, so not sure who has more bandwidth? This is the main table we need for the MBR so top priority of the tickets I'll be sending your way. Also -- I don't think Xuan has Github access so I've sent the text to her via slack in case she wants to review (as a listed dataset owner). Please don't merge until I hear back!

**Comment by skahmann3** [comment]
Xuan is good with the proposed changes. So we should be good to move forward on this

**Comment by alekhyamoz** [comment]
LGTM. @skahmann3 are there any downstream tables that need to be updated as well? if not, once the changes are merged I can work on the backfills. How far back does the data need to be backfilled?

**Review by alekhyamoz — APPROVED** [review]

**Comment by skahmann3** [comment]
@alekhyamoz Thank you! No downstream dependencies and please backfill table in it's entirety -- so back to 2018-01-01

**Pull request merged**
