### PR TITLE
bug: global_internet_outages removed client_id from group by for ssl_error_prop

### PR DESCRIPTION
**Pull request by kik-kik**
# bug: global_internet_outages removed client_id from group by for ssl_error_prop

Checklist for reviewer:

- [ ] Commits should reference a bug or github issue, if relevant (if a bug is referenced, the pull request should include the bug number in the title)
- [ ] If the PR comes from a fork, trigger integration CI tests by running the [Push to upstream workflow](https://github.com/mozilla/bigquery-etl/actions/workflows/push-to-upstream.yml) and provide the `<username>:<branch>` of the fork as parameter. The parameter will also show up
in the logs of the `manual-trigger-required-for-fork` CI task together with more detailed instructions.
- [ ] If adding a new field to a query, ensure that the schema and dependent downstream schemas have been updated

For modifications to schemas in restricted namespaces (see [`CODEOWNERS`](/CODEOWNERS)):
- [ ] Follow the [change control procedure](https://docs.google.com/document/d/1TTJi4ht7NuzX6BPG_KTr6omaZg70cEpxe9xlpfnHj9k/edit#heading=h.ttegrcfy18ck)

### CODE REVIEW

**Comment by Dexterp37** [comment]
> @Dexterp37 we could test after merging by running a query to check for duplication store the result and re-run for the same partition (as it should overwrite it with new logic) and see if duplication for that partition still exists.

I was planning on taking this to a test-drive by manually running the query on BigQuery and running a couple of existing analyses (known outages we detected). I'll do next week :)

**Review by Dexterp37 — APPROVED** [review]
I took a quick look and this seems to work good :-) Thanks !

**Comment by kik-kik** [comment]
@Dexterp37 do we plan to re-run the job for historical data or do we just leave the duplication for the past runs?

**Comment by Dexterp37** [comment]
> @Dexterp37 do we plan to re-run the job for historical data or do we just leave the duplication for the past runs?

I think it's ok to leave it for the past runs, but thanks for asking.

**Comment by kik-kik** [comment]
ok cool, thanks!

**Pull request merged**
