### PR TITLE
separate the test windows for mean and range data validation checks

### PR DESCRIPTION
**Pull request by chelseatroy**
OKAY!

We are replacing one column, which used to dictate the test windows for both mean and range, with two columns, that allow those to be adjusted separately.

We are removing the old column because keeping it would be confusing. We can move the old data into the new columns to preserve clarity and accuracy.

This is a new table with zero dependencies that currently only is used for monitoring by three people who are all aware this change is being made. So, though it is technically backward-breaking due to.the removal of a column, it is "safe" and should not require a change request or a new version of the table.

There is some SQL that needs to be run in prod to get the schema there to match this change. Here it is, divided up into teeny parts for legibility and risk mitigation:

```
ALTER TABLE `moz-fx-data-shared-prod.search_terms_derived.search_term_data_validation_reports_v1`
ADD COLUMN range_test_window_num_days integer;

UPDATE `moz-fx-data-shared-prod.search_terms_derived.search_term_data_validation_reports_v1`
SET range_test_window_num_days = test_window_num_days;

ALTER TABLE `moz-fx-data-shared-prod.search_terms_derived.search_term_data_validation_reports_v1`
ADD COLUMN mean_test_window_num_days integer;

UPDATE `moz-fx-data-shared-prod.search_terms_derived.search_term_data_validation_reports_v1`
SET mean_test_window_num_days = test_window_num_days;

ALTER TABLE `moz-fx-data-shared-prod.search_terms_derived.search_term_data_validation_reports_v1`
DROP COLUMN test_window_num_days;
```

Thank you! 

Checklist for reviewer:

- [ ] Commits should reference a bug or github issue, if relevant (if a bug is referenced, the pull request should include the bug number in the title).
- [ ] If the PR comes from a fork, trigger integration CI tests by running the [Push to upstream workflow](https://github.com/mozilla/bigquery-etl/actions/workflows/push-to-upstream.yml) and provide the `<username>:<branch>` of the fork as parameter. The parameter will also show up
in the logs of the `manual-trigger-required-for-fork` CI task together with more detailed instructions.
- [ ] If adding a new field to a query, ensure that the schema and dependent downstream schemas have been updated.
- [ ] When adding a new derived dataset, ensure that data is not available already (fully or partially) and recommend extending an existing dataset in favor of creating new ones. Data can be available in the [bigquery-etl repository](https://github.com/mozilla/bigquery-etl), [looker-hub](https://github.com/mozilla/looker-hub) or in [looker-spoke-default](https://github.com/mozilla/looker-spoke-default/tree/e1315853507fc1ac6e78d252d53dc8df5f5f322b).

For modifications to schemas in restricted namespaces (see [`CODEOWNERS`](/CODEOWNERS)):
- [ ] Follow the [change control procedure](https://docs.google.com/document/d/1TTJi4ht7NuzX6BPG_KTr6omaZg70cEpxe9xlpfnHj9k/edit#heading=h.ttegrcfy18ck)

### CODE REVIEW

**Review by whd — COMMENTED** [review]
I'm comfortable given the context with running the commands in this PR but would like @mreid-moz to confirm or weigh in on the slack thread or here before proceeding. That will also mostly serve as change control as the ultimate approval is from the same source (but without a corresponding jira ticket).

I'll note that using [DELETE](https://cloud.google.com/bigquery/docs/managing-table-schemas#delete_a_column) is a beta feature of BQ and therefore our usage should be governed by https://docs.google.com/document/d/1pvIiyk7Kwr6C66LlPzOhjlIq8gQkZCw8I4OIYohazD8/edit. If this table were in a more critical path I would have some concerns about using it, but for this case I think it's fine.

**Comment by mreid-moz** [comment]
This sounds good go me 👍

**Comment by chelseatroy** [comment]
> I assume `WHERE true` is the intent but want to double check before I run it.

@whd correct! Thank you :)

**Review by whd — APPROVED** [review]
All SQL statements have been run.

**Pull request merged**
