### PR TITLE
Skip dag validation if unmodified

### PR DESCRIPTION
**Pull request by relud**
using a modified version of the step we use to skip tests in gcp-ingestion: https://github.com/mozilla/gcp-ingestion/blob/329c0fa/.circleci/config.yml#L48-L67

### CODE REVIEW

**Review by jklukas — CHANGES_REQUESTED** [review]
The purpose of this job is different from the example we're following from gcp-ingestion.

From my experience, `validate-dags` regularly catches cases where a new query has been added with `scheduling` metadata, but the PR author hasn't run the `bqetl dag generate` machinery locally and checked in changes. The success of this task depends on the content of `sql/` and `dags/` being in sync.

**Comment by relud** [comment]
> From my experience, `validate-dags` regularly catches cases where a new query has been added with `scheduling` metadata, but the PR author hasn't run the `bqetl dag generate` machinery locally and checked in changes. The success of this task depends on the content of `sql/` and `dags/` being in sync.

perhaps you are confusing this job with `verify-dags-up-to-date`?

**Comment by jklukas** [comment]
> perhaps you are confusing this job with verify-dags-up-to-date?

Probably. Will look again.

**Review by jklukas — APPROVED** [review]
This makes perfect sense now. Thank you for the polite redirection.

**Pull request merged**
