### PR TITLE
 Bug 1741487 - Rename url2 and related fields in stable views

### PR DESCRIPTION
**Pull request by akkomar**
Checklist for reviewer:

- [ ] Commits should reference a bug or github issue, if relevant (if a bug is referenced, the pull request should include the bug number in the title).
- [ ] If the PR comes from a fork, trigger integration CI tests by running the [Push to upstream workflow](https://github.com/mozilla/bigquery-etl/actions/workflows/push-to-upstream.yml) and provide the `<username>:<branch>` of the fork as parameter. The parameter will also show up
in the logs of the `manual-trigger-required-for-fork` CI task together with more detailed instructions.
- [ ] If adding a new field to a query, ensure that the schema and dependent downstream schemas have been updated.
- [ ] When adding a new derived dataset, ensure that data is not available already (fully or partially) and recommend extending an existing dataset in favor of creating new ones. Data can be available in the [bigquery-etl repository](https://github.com/mozilla/bigquery-etl), [looker-hub](https://github.com/mozilla/looker-hub) or in [looker-spoke-default](https://github.com/mozilla/looker-spoke-default/tree/e1315853507fc1ac6e78d252d53dc8df5f5f322b).

For modifications to schemas in restricted namespaces (see [`CODEOWNERS`](https://github.com/mozilla/bigquery-etl/blob/main/CODEOWNERS)):
- [ ] Follow the [change control procedure](https://docs.google.com/document/d/1TTJi4ht7NuzX6BPG_KTr6omaZg70cEpxe9xlpfnHj9k/edit#heading=h.ttegrcfy18ck)

### CODE REVIEW

**Comment by akkomar** [comment]
Let's hold on with merging this until I prepare an announcement message.

**Comment by akkomar** [comment]
I'm converting this back to draft - staging tests show that we've missed a case of a table that has `url2` field and doesn't have `url` (e.g. `.org_mozilla_firefox_stable.cookie_banner_report_site_v1`).

**Comment by kik-kik** [comment]
Opened a follow-PR on a more recent branch so that all the unwanted and unrelated changes are not being shown in the git diff:
https://github.com/mozilla/bigquery-etl/pull/4028

**Comment by kik-kik** [comment]
Closed in favor of: PR#https://github.com/mozilla/bigquery-etl/pull/4028

**Pull request closed without merging**
