### PR TITLE
Try to fully specify `metrics` fields to select in Glean union views

### PR DESCRIPTION
**Pull request by sean-rose**
To try to avoid problems when the underlying table/view schemas change due to new metrics being added.

---
Checklist for reviewer:

- [ ] Commits should reference a bug or github issue, if relevant (if a bug is referenced, the pull request should include the bug number in the title).
- [ ] If the PR comes from a fork, trigger integration CI tests by running the [Push to upstream workflow](https://github.com/mozilla/bigquery-etl/actions/workflows/push-to-upstream.yml) and provide the `<username>:<branch>` of the fork as parameter. The parameter will also show up
in the logs of the `manual-trigger-required-for-fork` CI task together with more detailed instructions.
- [ ] If adding a new field to a query, ensure that the schema and dependent downstream schemas have been updated.
- [ ] When adding a new derived dataset, ensure that data is not available already (fully or partially) and recommend extending an existing dataset in favor of creating new ones. Data can be available in the [bigquery-etl repository](https://github.com/mozilla/bigquery-etl), [looker-hub](https://github.com/mozilla/looker-hub) or in [looker-spoke-default](https://github.com/mozilla/looker-spoke-default/tree/e1315853507fc1ac6e78d252d53dc8df5f5f322b).

For modifications to schemas in restricted namespaces (see [`CODEOWNERS`](https://github.com/mozilla/bigquery-etl/blob/main/CODEOWNERS)):
- [ ] Follow the [change control procedure](https://docs.google.com/document/d/1TTJi4ht7NuzX6BPG_KTr6omaZg70cEpxe9xlpfnHj9k/edit#heading=h.ttegrcfy18ck)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4100)

### CODE REVIEW

**Review by scholtzan — APPROVED** [review]

**Comment by sean-rose** [comment]
I was worried doing this might cause BigQuery to always scan all `metrics` columns since they're being restructured in the view query, but in a minimal test dry-running queries to count the number of rows with a particular boolean metric set to true BigQuery reported the same number of bytes scanned both with and without this change.  So it appears BigQuery is successfully able to optimize through the restructuring logic and only scan the data that's needed (at least with simple `STRUCT()` calls like in this case).

**Comment by sean-rose** [comment]
One thing we'll need to watch out for is this can make the view SQL significantly longer.  For example, with this change [sql/moz-fx-data-shared-prod/fenix/metrics/view.sql](https://github.com/mozilla/bigquery-etl/blob/generated-sql/sql/moz-fx-data-shared-prod/fenix/metrics/view.sql) would increase from ~99k characters to ~225k characters, which would be getting close to BigQuery's [256k character limit for view SQL](https://cloud.google.com/bigquery/quotas#view_limits) (I'm going to ask Google whether that limit can be increased).

**Comment by BenWu** [comment]
You may have already figured this out but `use_counters` is even bigger than the metrics view (783k characters).  whd pointed out that we should be able to get jenkins to trigger artifact deployment soon so this might no longer be an issue soon, although it would still be a bit of ETL quirkiness https://bugzilla.mozilla.org/show_bug.cgi?id=1883727#c3

**Comment by sean-rose** [comment]
> You may have already figured this out but `use_counters` is even bigger than the metrics view (783k characters). whd pointed out that we should be able to get jenkins to trigger artifact deployment soon so this might no longer be an issue soon, although it would still be a bit of ETL quirkiness https://bugzilla.mozilla.org/show_bug.cgi?id=1883727#c3

Yeah, with this change `fenix.use_counters` ends up being 783k characters and `focus_android.use_counters` ends up being 469k characters. I missed those initially because I was only running the `glean_usage` generator locally without running the `stable_views` generator first.

I'm going to add a workaround for that, then ping you and @scholtzan for re-review, and y'all can weigh in on whether it's worth merging this, or if it would be better to just wait for the Jenkins-triggered artifact deployment.

**Review by BenWu — COMMENTED** [review]
This makes sense but I would lean towards fixing the schema deploy timing issue rather than adding more code here, especially since this is just a best effort solution which doesn't work for every view.  My opinion is that effort is better spent pushing [bug 1883727](https://bugzilla.mozilla.org/show_bug.cgi?id=1883727) forward rather than patching these views up but I'm not opposed to these changes

**Review by scholtzan — APPROVED** [review]

**Pull request merged**
