### PR TITLE
add query_id and username columns to bigquery_usage_v2 table - joinin…

### PR DESCRIPTION
**Pull request by Marlene-M-Hirose**
…g JOBS_BY_ORG and JOBS_BY_PROJECT tables

We want to add query_id and username columns from `region-us.INFORMATION_SCHEMA.JOBS_BY_PROJECT` to the `moz-fx-data-shared-prod.monitoring_derived.bigquery_usage_v2` table. This will allow us to deprecate the `moz-fx-data-shared-prod.monitoring_derived.bigquery_usage_v1` table

_This bigquery_table_usage_v2 table originally was connected to the bigquery provided table: region-us.INFORMATION_SCHEMA.JOBS_BY_PROJECT. It no longer is. We are using the `moz-fx-data-shared-prod.monitoring_derived.jobs_by_organization_v1` table. **Query_id and username columns have been added.**_

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1420)

### CODE REVIEW

**Comment by whd** [comment]
I think this is going to need some adjustment. Here's an example of what I would expect the generated SQL to look like:

```sql
WITH
  jobs_by_org AS (
  SELECT
    t1.project_id AS source_project,
    DATE('2023-08-16') AS creation_date,
    job_id,
    job_type,
    reservation_id,
    cache_hit,
    state,
    statement_type,
    referenced_tables,
    destination_table.project_id AS destination_project_id,
    destination_table.dataset_id AS destination_dataset_id,
    destination_table.table_id AS destination_table_id,
    user_email,
    end_time-start_time AS task_duration,
    ROUND(total_bytes_processed / 1024 / 1024 / 1024 / 1024, 4) AS total_terabytes_processed,
    ROUND(total_bytes_billed / 1024 / 1024 / 1024 / 1024, 4) AS total_terabytes_billed,
    total_slot_ms,
    error_result.location AS error_location,
    error_result.reason AS error_reason,
    error_result.message AS error_message,
    query_info.resource_warning AS resource_warning,
  FROM
    `region-us.INFORMATION_SCHEMA.JOBS_BY_ORGANIZATION` AS t1
  LEFT JOIN
    UNNEST(referenced_tables) AS referenced_tables
  WHERE
    DATE(creation_time) = '2023-08-16'
    AND (t1.project_id IN UNNEST(["mozdata","moz-fx-data-shared-prod","moz-fx-data-marketing-prod","moz-fx-data-bq-data-science"])
      OR referenced_tables.project_id IN UNNEST(["mozdata","moz-fx-data-shared-prod","moz-fx-data-marketing-prod","moz-fx-data-bq-data-science"])
      OR destination_table.project_id IN UNNEST(["mozdata","moz-fx-data-shared-prod","moz-fx-data-marketing-prod","moz-fx-data-bq-data-science"])) ),
  jobs_by_project AS (
  SELECT
    "moz-fx-data-shared-prod" AS source_project,
    DATE('2023-08-16') AS creation_date,
    job_id,
    user_email,
    REGEXP_EXTRACT(query, r"Username: (.*?),") AS username,
    REGEXP_EXTRACT(query, r"Query ID: (\w+), ") AS query_id,
  FROM
    `moz-fx-data-shared-prod.region-us.INFORMATION_SCHEMA.JOBS_BY_PROJECT`
  LEFT JOIN
    UNNEST(referenced_tables) AS referenced_tables
  WHERE
    DATE(creation_time) = '2023-08-16'
  UNION ALL
  SELECT
    "moz-fx-data-marketing-prod" AS source_project,
    DATE('2023-08-16') AS creation_date,
    job_id,
    user_email,
    REGEXP_EXTRACT(query, r"Username: (.*?),") AS username,
    REGEXP_EXTRACT(query, r"Query ID: (\w+), ") AS query_id,
  FROM
    `moz-fx-data-marketing-prod.region-us.INFORMATION_SCHEMA.JOBS_BY_PROJECT`
  LEFT JOIN
    UNNEST(referenced_tables) AS referenced_tables
  WHERE
    DATE(creation_time) = '2023-08-16'
  UNION ALL
  SELECT
    "mozdata" AS source_project,
    DATE('2023-08-16') AS creation_date,
    job_id,
    user_email,
    REGEXP_EXTRACT(query, r"Username: (.*?),") AS username,
    REGEXP_EXTRACT(query, r"Query ID: (\w+), ") AS query_id,
  FROM
    `mozdata.region-us.INFORMATION_SCHEMA.JOBS_BY_PROJECT`
  LEFT JOIN
    UNNEST(referenced_tables) AS referenced_tables
  WHERE
    DATE(creation_time) = '2023-08-16' )
SELECT
  jo.source_project,
  jo.creation_date,
  jo.job_id,
  jo.job_type,
  jo.reservation_id,
  jo.cache_hit,
  jo.state,
  jo.statement_type,
  jp.query_id,
  referenced_tables.project_id AS reference_project_id,
  referenced_tables.dataset_id AS reference_dataset_id,
  referenced_tables.table_id AS reference_table_id,
  jo.destination_project_id,
  jo.destination_dataset_id,
  jo.destination_table_id,
  jo.user_email,
  jp.username,
  jo.task_duration,
  jo.total_terabytes_processed,
  jo.total_terabytes_billed,
  jo.total_slot_ms,
  jo.error_location,
  jo.error_reason,
  jo.error_message,
  jo.resource_warning
FROM
  jobs_by_org jo
LEFT JOIN
  jobs_by_project jp
USING
  (source_project,
    creation_date,
    job_id)
WHERE
  creation_date = '2023-08-16'
```

Basically, there is some fiddling with `UNNEST(referenced_tables) AS referenced_tables` and  you need to iterate over the individual projects to achieve what was previously achieved by running multiple queries with [WRITE_APPEND](https://github.com/mozilla/bigquery-etl/blob/main/sql/moz-fx-data-shared-prod/monitoring_derived/bigquery_usage_v1/query.py#L81). I think the above query might introduce some duplicates but that's the gist of it.

**Comment by Marlene-M-Hirose** [comment]
Ok, I will adjust the code. Thank you

**Comment by Marlene-M-Hirose** [comment]
I looked at some of the data in the tables and it looks like I will have to join on:
            source_project,
            creation_date, 
            job_id, 
            reference_project_id, 
            reference_dataset_id, 
            reference_table_id

**Comment by whd** [comment]
Now that this isn't using `JOBS_BY_ORGANIZATION` directly you can remove https://github.com/mozilla/bigquery-etl/blob/main/CODEOWNERS#L18 to no longer require DSRE review. Once that line is removed I'll r+ the PR for strictly the change control aspects.

One thing to note is that in future (not now) if you're ever writing queries that use `JOBS_BY_PROJECT` for projects other than those in `DEFAULT_PROJECTS`, that's access that Airflow has but that DE doesn't and would be subject to the same restrictions as queries of `JOBS_BY_ORGANIZATION`.

**Review by whd — APPROVED** [review]

**Pull request merged**
