### PR TITLE
Added a filter to only include playstore data

### PR DESCRIPTION
**Pull request by soGaussian**
In keeping the bottom of the funnel consistent with the upper funnel, we have to only include installs from play store in the bottom of the funnel metrics

Checklist for reviewer:

- [ ] Commits should reference a bug or github issue, if relevant (if a bug is referenced, the pull request should include the bug number in the title).
- [ ] If the PR comes from a fork, trigger integration CI tests by running the [Push to upstream workflow](https://github.com/mozilla/bigquery-etl/actions/workflows/push-to-upstream.yml) and provide the `<username>:<branch>` of the fork as parameter. The parameter will also show up
in the logs of the `manual-trigger-required-for-fork` CI task together with more detailed instructions.
- [ ] If adding a new field to a query, ensure that the schema and dependent downstream schemas have been updated.
- [ ] When adding a new derived dataset, ensure that data is not available already (fully or partially) and recommend extending an existing dataset in favor of creating new ones. Data can be available in the [bigquery-etl repository](https://github.com/mozilla/bigquery-etl), [looker-hub](https://github.com/mozilla/looker-hub) or in [looker-spoke-default](https://github.com/mozilla/looker-spoke-default/tree/e1315853507fc1ac6e78d252d53dc8df5f5f322b).

For modifications to schemas in restricted namespaces (see [`CODEOWNERS`](https://github.com/mozilla/bigquery-etl/blob/main/CODEOWNERS)):
- [ ] Follow the [change control procedure](https://docs.google.com/document/d/1TTJi4ht7NuzX6BPG_KTr6omaZg70cEpxe9xlpfnHj9k/edit#heading=h.ttegrcfy18ck)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1849)

### CODE REVIEW

**Comment by kik-kik** [comment]
@soGaussian if this filter is needed, should we also include it in [funnel_retention_clients_week_2_v1](https://github.com/mozilla/bigquery-etl/blob/main/sql/moz-fx-data-shared-prod/fenix_derived/funnel_retention_clients_week_2_v1/query.sql)?

**Comment by soGaussian** [comment]
So the week 2 table is not used in the funnel and so I cannot say. but we should expose the filter there as well. I believe the consensus was not to filter it out but to expose the column in the final table. Is this accurate @gkabbz

**Comment by kik-kik** [comment]
> So the week 2 table is not used in the funnel and so I cannot say. but we should expose the filter there as well. I believe the consensus was not to filter it out but to expose the column in the final table. Is this accurate @gkabbz

Actually, it is by the downstream view @soGaussian. We should keep both of those queries in sync. Eventually, we can create some sort of "generator" to auto-generate these queries for each time frame we want.

**Comment by kik-kik** [comment]
Superseded by https://github.com/mozilla/bigquery-etl/pull/4561

**Pull request closed without merging**
