### PR TITLE
regrets-reporter queries updated to use stable tables

### PR DESCRIPTION
**Pull request by kik-kik**
# regrets-reporter queries updated to use stable tables

- Queries have been updated to use stable tables.
- Since the init.sql was modified and no additional data was appended I'd suggest we drop the old table (or truncate) and re-run the init script to recreate the table depending on this approach we take.

resolves #2635 

---
Checklist for reviewer:

- [ ] Commits should reference a bug or github issue, if relevant (if a bug is referenced, the pull request should include the bug number in the title)
- [ ] If the PR comes from a fork, trigger integration CI tests by running the [Push to upstream workflow](https://github.com/mozilla/bigquery-etl/actions/workflows/push-to-upstream.yml) and provide the `<username>:<branch>` of the fork as parameter. The parameter will also show up
in the logs of the `manual-trigger-required-for-fork` CI task together with more detailed instructions.
- [ ] If adding a new field to a query, ensure that the schema and dependent downstream schemas have been updated

For modifications to schemas in restricted namespaces (see [`CODEOWNERS`](/CODEOWNERS)):
- [ ] Follow the [change control procedure](https://docs.google.com/document/d/1TTJi4ht7NuzX6BPG_KTr6omaZg70cEpxe9xlpfnHj9k/edit#heading=h.ttegrcfy18ck)

### CODE REVIEW

**Comment by kik-kik** [comment]
@jklukas Could you please double check if I missed anything? Thanks! 🙇

**Review by jklukas — APPROVED** [review]

**Comment by kik-kik** [comment]
@whd apologies to bother you again with this. Could you please re-run the init.sql and overwrite the current table? Wrong underlying tables were used.

Thanks! 🙇

**Comment by whd** [comment]
I've run the `init.sql` query.

```
This statement replaced the table named moz-fx-data-shared-prod:regrets_reporter_derived.regrets_reporter_summary_v1. 
```

**Comment by kik-kik** [comment]
Amazing, thank you @whd 🙇

**Pull request merged**
