### PR TITLE
Include missing required keys in schema error paths

### PR DESCRIPTION
**Pull request by sean-rose**
Checklist for reviewer:

- [ ] Commits should reference a bug or github issue, if relevant (if a bug is referenced, the pull request should include the bug number in the title)
- [ ] If the PR comes from a fork, trigger integration CI tests by running the [Push to upstream workflow](https://github.com/mozilla/bigquery-etl/actions/workflows/push-to-upstream.yml) and provide the `<username>:<branch>` of the fork as parameter. The parameter will also show up
in the logs of the `manual-trigger-required-for-fork` CI task together with more detailed instructions.
- [ ] If adding a new field to a query, ensure that the schema and dependent downstream schemas have been updated

For modifications to schemas in restricted namespaces (see [`CODEOWNERS`](/CODEOWNERS)):
- [ ] Follow the [change control procedure](https://docs.google.com/document/d/1TTJi4ht7NuzX6BPG_KTr6omaZg70cEpxe9xlpfnHj9k/edit#heading=h.ttegrcfy18ck)

### CODE REVIEW

**Comment by sean-rose** [comment]
How far back should we backfill  `schema_error_counts_v2`?

**Review by scholtzan — APPROVED** [review]
Looks good.

I think the dashboard looks at the last 14 days, so backfilling 2 weeks might be enough here?

**Comment by sean-rose** [comment]
> I think the dashboard looks at the last 14 days, so backfilling 2 weeks might be enough here?

The "**All schema errors (last 14 days)**" tile is that way, but it looks like the "**Top Schema Errors**" tile is following the submission date filter (which defaults to 90 days), and I'm not sure about the "**Top schema errors normalized**" tile (I'm confused how Looker decides whether a filter applies or not).

So I guess backfilling 90 days would give the cleanest result.

**Comment by sean-rose** [comment]
I backfilled `schema_error_counts_v2` back to 2022-05-01.

**Pull request merged**
