### PR TITLE
RS-346 Add AdM forecasting table schema

### PR DESCRIPTION
**Pull request by akkomar**
This fixes omission from https://github.com/mozilla/bigquery-etl/pull/3264.

In order to deploy the schema the following command needs to be executed by someone with `bigquery.tables.create` permission on dataset `moz-fx-data-shared-prod:contextual_services_derived`:
```
./bqetl query schema deploy contextual_services_derived.adm_forecasting_v1 --ignore-dryrun-skip --use-cloud-function=False
```

Checklist for reviewer:

- [ ] Commits should reference a bug or github issue, if relevant (if a bug is referenced, the pull request should include the bug number in the title)
- [ ] If the PR comes from a fork, trigger integration CI tests by running the [Push to upstream workflow](https://github.com/mozilla/bigquery-etl/actions/workflows/push-to-upstream.yml) and provide the `<username>:<branch>` of the fork as parameter. The parameter will also show up
in the logs of the `manual-trigger-required-for-fork` CI task together with more detailed instructions.
- [ ] If adding a new field to a query, ensure that the schema and dependent downstream schemas have been updated

For modifications to schemas in restricted namespaces (see [`CODEOWNERS`](/CODEOWNERS)):
- [ ] Follow the [change control procedure](https://docs.google.com/document/d/1TTJi4ht7NuzX6BPG_KTr6omaZg70cEpxe9xlpfnHj9k/edit#heading=h.ttegrcfy18ck)

### CODE REVIEW

**Comment by akkomar** [comment]
@whd I think we now lean towards table deploys via schema+metadata route vs. init.sql, but if the latter is preferred here for easier execution I can add it too.

**Review by whd — APPROVED** [review]
I ran this, so the table should be created now.

**Comment by skahmann3** [comment]
When trying to query the new table, I get this error:

Access Denied: Table moz-fx-data-shared-prod:contextual_services_derived.adm_forecasting_v1: User does not have permission to query table moz-fx-data-shared-prod:contextual_services_derived.adm_forecasting_v1, or perhaps it does not exist in location US. 

I have contextual services permissions, I can still query event_aggregates without issue, so any idea what could be causing this?

**Comment by skahmann3** [comment]
I can query the table today, so this PR is officially wrapped!

**Pull request merged**
