### PR TITLE
For #3430 - Improve clarity of documentation around Dirichlet UDF

### PR DESCRIPTION
**Pull request by perrymcmanis144**
As per Slack, I have made this VERY explicit, such that someone who reads this without much context should hopefully not mixup the lowercase p/k with the upper case ones.

Checklist for reviewer:

- [x] Commits should reference a bug or github issue, if relevant (if a bug is referenced, the pull request should include the bug number in the title).
- [ ] If the PR comes from a fork, trigger integration CI tests by running the [Push to upstream workflow](https://github.com/mozilla/bigquery-etl/actions/workflows/push-to-upstream.yml) and provide the `<username>:<branch>` of the fork as parameter. The parameter will also show up
in the logs of the `manual-trigger-required-for-fork` CI task together with more detailed instructions.
- [ ] If adding a new field to a query, ensure that the schema and dependent downstream schemas have been updated.
- [ ] When adding a new derived dataset, ensure that data is not available already (fully or partially) and recommend extending an existing dataset in favor of creating new ones. Data can be available in the [bigquery-etl repository](https://github.com/mozilla/bigquery-etl), [looker-hub](https://github.com/mozilla/looker-hub) or in [looker-spoke-default](https://github.com/mozilla/looker-spoke-default/tree/e1315853507fc1ac6e78d252d53dc8df5f5f322b).

For modifications to schemas in restricted namespaces (see [`CODEOWNERS`](/CODEOWNERS)):
- [ ] Follow the [change control procedure](https://docs.google.com/document/d/1TTJi4ht7NuzX6BPG_KTr6omaZg70cEpxe9xlpfnHj9k/edit#heading=h.ttegrcfy18ck)

### CODE REVIEW

**Comment by edugfilho** [comment]
Excellent. LGTM except for lint complaining that some lines got too lengthy:
```
./sql/mozfun/glam/histogram_fill_buckets_dirichlet/metadata.yaml
  9:81      error    line too long (83 > 80 characters)  (line-length)
  11:81     error    line too long (83 > 80 characters)  (line-length)
  12:81     error    line too long (86 > 80 characters)  (line-length)
  17:81     error    line too long (96 > 80 characters)  (line-length)
  ```

**Comment by perrymcmanis144** [comment]
> Excellent. LGTM except for lint complaining that some lines got too lengthy:
> 
> ```
> ./sql/mozfun/glam/histogram_fill_buckets_dirichlet/metadata.yaml
>   9:81      error    line too long (83 > 80 characters)  (line-length)
>   11:81     error    line too long (83 > 80 characters)  (line-length)
>   12:81     error    line too long (86 > 80 characters)  (line-length)
>   17:81     error    line too long (96 > 80 characters)  (line-length)
> ```

The URL was too long so I let that slip, but I got it fixed

**Review by edugfilho — APPROVED** [review]
Fixed some yaml lint stuff and it's looking good now.
Thank you for improving this!

**Comment by perrymcmanis144** [comment]
TYVM @edugfilho , not having a fully functional local BQ setup is a pain when it comes to having to pass all the linter checks so I appreciate the help on this front.

I will close the issue as done.

**Pull request merged**
