### PR TITLE
Regenerate DAGs after #3870

### PR DESCRIPTION
**Pull request by sean-rose**
#3870 changed ETL but didn't regenerate the DAGs.

---
Checklist for reviewer:

- [ ] Commits should reference a bug or github issue, if relevant (if a bug is referenced, the pull request should include the bug number in the title).
- [ ] If the PR comes from a fork, trigger integration CI tests by running the [Push to upstream workflow](https://github.com/mozilla/bigquery-etl/actions/workflows/push-to-upstream.yml) and provide the `<username>:<branch>` of the fork as parameter. The parameter will also show up
in the logs of the `manual-trigger-required-for-fork` CI task together with more detailed instructions.
- [ ] If adding a new field to a query, ensure that the schema and dependent downstream schemas have been updated.
- [ ] When adding a new derived dataset, ensure that data is not available already (fully or partially) and recommend extending an existing dataset in favor of creating new ones. Data can be available in the [bigquery-etl repository](https://github.com/mozilla/bigquery-etl), [looker-hub](https://github.com/mozilla/looker-hub) or in [looker-spoke-default](https://github.com/mozilla/looker-spoke-default/tree/e1315853507fc1ac6e78d252d53dc8df5f5f322b).

For modifications to schemas in restricted namespaces (see [`CODEOWNERS`](https://github.com/mozilla/bigquery-etl/blob/main/CODEOWNERS)):
- [ ] Follow the [change control procedure](https://docs.google.com/document/d/1TTJi4ht7NuzX6BPG_KTr6omaZg70cEpxe9xlpfnHj9k/edit#heading=h.ttegrcfy18ck)

### CODE REVIEW

**Comment by sean-rose** [comment]
CI disagrees with the regenerated DAGs, but I've double-checked things locally by setting up a clean bqetl environment locally from a fresh clone of the `main` branch, then running `bqetl dag generate` and it makes the same DAG updates as this PR.  Somehow CI is out of sync with reality? 😕

**Review by scholtzan — APPROVED** [review]

**Comment by scholtzan** [comment]
ah, are those based on sql_generators?

**Comment by scholtzan** [comment]
I guess this can actually be closed. `main` is looking good

**Comment by sean-rose** [comment]
> I guess this can actually be closed. `main` is looking good

Confirmed, my bad.  I didn't realize it was necessary to run `bqetl generate all` before regenerating DAGs locally.

**Pull request closed without merging**
