### PR TITLE
Generate query tests with pytest plugin

### PR DESCRIPTION
**Pull request by relud**
so that we can do things like `pytest tests/telemetry_derived`

### CODE REVIEW

**Comment by jklukas** [comment]
At a high level, this looks great and I look forward to better test naming and being able to do targeted test runs. That said, it's difficult to deeply understand this without more context on how pytest plugins work. It looks like there are several things failing in CI; if you can work those down, this should be good to merge. The code itself looks quite understandable and maintainable.

**Comment by relud** [comment]
> It looks like there are several things failing in CI

`>_<` I thought I'd resolved those before I marked this ready, my bad. it's working now, and a bit more readable.

**Comment by jklukas** [comment]
Is the removal of the clients_last_seen test directory intentional?

**Comment by relud** [comment]
> Is the removal of the clients_last_seen test directory intentional?

yes, it's not actually a valid test, and it's not compatible with clients_last_seen anymore either.

**Pull request merged**
