### PR TITLE
Add new column to job metadata table schema in updated version of table.

### PR DESCRIPTION
**Pull request by chelseatroy**
1. [This one](https://github.com/mozilla-services/cloudops-infra/pull/4472) that switches the script in cloudops-infra to point to the new version of this table
2. [This one](https://github.com/mozilla/search-terms-sanitization/pull/10) that changes the script to deposit data following the new schema

Because this is a restricted access table, unforch I cannot take care of running the SQL. I feel bad troubling DSRE to run SQL _for_ me, so...I wonder how @mreid-moz might speculate on the possibility of letting DEs with cat 3 access run SQL on tables like these in prod.

In the meantime, I can at least write you the SQL, and in this case there's hardly any of it:

```
ALTER TABLE moz-fx-data-shared-prod.search_terms_derived.sanitization_job_metadata_v2
ADD COLUMN total_search_terms_appearing_in_allow_list INTEGER;
```

Checklist for reviewer:

- [ ] Commits should reference a bug or github issue, if relevant (if a bug is referenced, the pull request should include the bug number in the title).
- [ ] If the PR comes from a fork, trigger integration CI tests by running the [Push to upstream workflow](https://github.com/mozilla/bigquery-etl/actions/workflows/push-to-upstream.yml) and provide the `<username>:<branch>` of the fork as parameter. The parameter will also show up
in the logs of the `manual-trigger-required-for-fork` CI task together with more detailed instructions.
- [ ] If adding a new field to a query, ensure that the schema and dependent downstream schemas have been updated.
- [ ] When adding a new derived dataset, ensure that data is not available already (fully or partially) and recommend extending an existing dataset in favor of creating new ones. Data can be available in the [bigquery-etl repository](https://github.com/mozilla/bigquery-etl), [looker-hub](https://github.com/mozilla/looker-hub) or in [looker-spoke-default](https://github.com/mozilla/looker-spoke-default/tree/e1315853507fc1ac6e78d252d53dc8df5f5f322b).

For modifications to schemas in restricted namespaces (see [`CODEOWNERS`](/CODEOWNERS)):
- [ ] Follow the [change control procedure](https://docs.google.com/document/d/1TTJi4ht7NuzX6BPG_KTr6omaZg70cEpxe9xlpfnHj9k/edit#heading=h.ttegrcfy18ck)

### CODE REVIEW

**Comment by whd** [comment]
@chelseatroy can you file a ticket like https://mozilla-hub.atlassian.net/browse/DSRE-899 for change control purposes?

**Review by whd — COMMENTED** [review]
I think we generally recommend for backwards compatible schema updates to reuse the existing table and suffix (i.e. a new table only needs to be created for a backwards-incompatible schema change).

@scholtzan is this documented anywhere? It's kind of implicit from the following statement on https://mozilla.github.io/bigquery-etl/reference/recommended_practices/#queries:

```
Queries that populate tables should always be named with a version suffix; we assume that future optimizations to the data representation may require schema-incompatible changes such as dropping columns
```

 For this PR, that would mean updating the v2 `init.sql` to include the new field and having DSRE run an `ALTER TABLE ADD COLUMN` statement to match the new `init.sql`. Fields are NULLable by default in BQ and this new field would also be NULLable. 

This would obviate https://github.com/mozilla-services/cloudops-infra/pull/4472.

**Comment by chelseatroy** [comment]
> I think we generally recommend for backwards compatible schema updates to reuse the existing table and suffix (i.e. a new table only needs to be created for a backwards-incompatible schema change).
> 
> @scholtzan is this documented anywhere? It's kind of implicit from the following statement on https://mozilla.github.io/bigquery-etl/reference/recommended_practices/#queries:
> 
> ```
> Queries that populate tables should always be named with a version suffix; we assume that future optimizations to the data representation may require schema-incompatible changes such as dropping columns
> ```
> 
> For this PR, that would mean updating the v2 `init.sql` to include the new field and having DSRE run an `ALTER TABLE ADD COLUMN` statement to match the new `init.sql`. Fields are NULLable by default in BQ and this new field would also be NULLable.
> 
> This would obviate [mozilla-services/cloudops-infra#4472](https://github.com/mozilla-services/cloudops-infra/pull/4472).

I am happy to do the change this way as opposed to creating a new table if folks deem that appropriate! If we confirm that that's the case I'll change the code in this PR 🙂

**Review by whd — APPROVED** [review]
I ran
```
ALTER TABLE `moz-fx-data-shared-prod.search_terms_derived.sanitization_job_metadata_v2`
ADD COLUMN total_search_terms_appearing_in_allow_list integer;
```

so this change should be in place now.

**Pull request merged**
