### PR TITLE
Ignore `jsonPayload.fields.id` column for `fxa_auth_events` (bugs 1791061, 1791062)

### PR DESCRIPTION
**Pull request by sean-rose**
It changed type from string to float in recent `moz-fx-fxa-prod-0712.fxa_prod_logs.docker_fxa_auth_20*` tables, which is breaking the `fxa_auth_events` ETL (bugs [1791061](https://bugzilla.mozilla.org/show_bug.cgi?id=1791061), [1791062](https://bugzilla.mozilla.org/show_bug.cgi?id=1791062)), and it doesn't appear to be populated for `amplitudeEvent` events anyway.

---
Checklist for reviewer:

- [ ] Commits should reference a bug or github issue, if relevant (if a bug is referenced, the pull request should include the bug number in the title)
- [ ] If the PR comes from a fork, trigger integration CI tests by running the [Push to upstream workflow](https://github.com/mozilla/bigquery-etl/actions/workflows/push-to-upstream.yml) and provide the `<username>:<branch>` of the fork as parameter. The parameter will also show up
in the logs of the `manual-trigger-required-for-fork` CI task together with more detailed instructions.
- [ ] If adding a new field to a query, ensure that the schema and dependent downstream schemas have been updated

For modifications to schemas in restricted namespaces (see [`CODEOWNERS`](/CODEOWNERS)):
- [ ] Follow the [change control procedure](https://docs.google.com/document/d/1TTJi4ht7NuzX6BPG_KTr6omaZg70cEpxe9xlpfnHj9k/edit#heading=h.ttegrcfy18ck)

### CODE REVIEW

**Comment by kik-kik** [comment]
Are you sure we can null this field @sean-rose ?

**Review by relud — APPROVED** [review]

**Comment by relud** [comment]
CI failure looks unrelated

**Comment by sean-rose** [comment]
> Are you sure we can null this field @sean-rose ?

Pretty sure.

Unfortunately due to the nature of the schema change and how BigQuery wildcard table queries work I can't easily query all matching tables to verify `jsonPayload.fields.id` is always null for `amplitudeEvent` events, but that has been the case for all of the ~10 days I've spot-checked.

Also, as far as I can tell `jsonPayload.fields.id` isn't currently used in any downstream ETL.

**Comment by relud** [comment]
> Unfortunately due to the nature of the schema change and how BigQuery wildcard table queries work I can't easily query all matching tables to verify `jsonPayload.fields.id` is always null for `amplitudeEvent` events, but that has been the case for all of the ~10 days I've spot-checked.

you should only need to spot-check days after the ETL started failing, because you can easily check the derived table for all days prior to that.

**Comment by sean-rose** [comment]
> > Unfortunately due to the nature of the schema change and how BigQuery wildcard table queries work I can't easily query all matching tables to verify `jsonPayload.fields.id` is always null for `amplitudeEvent` events, but that has been the case for all of the ~10 days I've spot-checked.
> 
> you should only need to spot-check days after the ETL started failing, because you can easily check the derived table for all days prior to that.

Good point!  Using that approach I've verified that `jsonPayload.fields.id` has been null for all `amplitudeEvent` events thus far.

**Pull request merged**
