### PR TITLE
DENG1546 -Add a derived dataset for serp events

### PR DESCRIPTION
**Pull request by alekhyamoz**
This is WIP until the query is finalized.
Note - The desktop_query.sql has not been templatized yet for ease of use by the DS

Checklist for reviewer:

- [ ] Commits should reference a bug or github issue, if relevant (if a bug is referenced, the pull request should include the bug number in the title).
- [ ] If the PR comes from a fork, trigger integration CI tests by running the [Push to upstream workflow](https://github.com/mozilla/bigquery-etl/actions/workflows/push-to-upstream.yml) and provide the `<username>:<branch>` of the fork as parameter. The parameter will also show up
in the logs of the `manual-trigger-required-for-fork` CI task together with more detailed instructions.
- [ ] If adding a new field to a query, ensure that the schema and dependent downstream schemas have been updated.
- [ ] When adding a new derived dataset, ensure that data is not available already (fully or partially) and recommend extending an existing dataset in favor of creating new ones. Data can be available in the [bigquery-etl repository](https://github.com/mozilla/bigquery-etl), [looker-hub](https://github.com/mozilla/looker-hub) or in [looker-spoke-default](https://github.com/mozilla/looker-spoke-default/tree/e1315853507fc1ac6e78d252d53dc8df5f5f322b).

For modifications to schemas in restricted namespaces (see [`CODEOWNERS`](https://github.com/mozilla/bigquery-etl/blob/main/CODEOWNERS)):
- [ ] Follow the [change control procedure](https://docs.google.com/document/d/1TTJi4ht7NuzX6BPG_KTr6omaZg70cEpxe9xlpfnHj9k/edit#heading=h.ttegrcfy18ck)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1605)

### CODE REVIEW

**Comment by dzeber** [comment]
Hi @alekhyamoz , thanks for opening this! I've made some updates to the query based on recent discussions. The main change is to unpivot the structure slightly to have multiple rows per impression ID.

I've also replaced `submission_date` with `submission_timestamp` to assist in joining against urlbar events, and replaced the literal date with `@submission_date`.

**Comment by pissac17** [comment]
@dzeber @alekhyamoz I noticed inconsistency in how num_clicks is being reported using this query (this could be due to the join used in` serp_events.` ). For instance, for impression_id _'41645c90-2e43-4000-bc64-973075ca2dd0'_ and _submission_date = '2023-09-22'_, I'm seeing only 5 num_clicks. However this query reports 222 num_clicks for this impression_id. Here's the query I used to test:

```
with test as 
(
SELECT client_info.client_id as client_id, submission_timestamp,
 (SELECT value FROM UNNEST(event_extra) WHERE key = 'impression_id') AS impression_id,
(SELECT 1 FROM UNNEST(event_extra) WHERE key = 'target' and value = 'ad_link') AS ad_link,
(SELECT 1 FROM UNNEST(event_extra) WHERE key = 'target' and value = 'ad_sitelink') AS ad_sitelink,
(SELECT 1 FROM UNNEST(event_extra) WHERE key = 'target' and value = 'ad_carousel') AS ad_carousel,
(SELECT 1 FROM UNNEST(event_extra) WHERE key = 'target'and value = 'ad_sidebar') AS ad_sidebar,
(SELECT 1 FROM UNNEST(event_extra) WHERE key = 'target' and value = 'refined_search_buttons') AS refined_search_buttons,
(SELECT 1 FROM UNNEST(event_extra) WHERE key = 'target'and value = 'shopping_tab') AS shopping_tab,
(SELECT 1 FROM UNNEST(event_extra) WHERE key = 'target' and value = 'incontent_searchbox') AS incontent_searchbox,
(SELECT 1 FROM UNNEST(event_extra) WHERE key = 'target'and value = 'non_ads_link') AS non_ads_link,

(SELECT 1 FROM UNNEST(event_extra) WHERE key = 'action'and value in ('clicked')) AS clicked,
(SELECT 1 FROM UNNEST(event_extra) WHERE key = 'action'and value in ('submitted')) AS submitted,
(SELECT 1 FROM UNNEST(event_extra) WHERE key = 'action'and value in ('expanded')) AS expanded



FROM

 `moz-fx-data-shared-prod.firefox_desktop.events_unnested`


WHERE
 event_category = "serp"

 AND event_name = "engagement"
 AND date(submission_timestamp) = '2023-09-22')

 select impression_id, sum(clicked) as num_clicked
 from test where impression_id = '41645c90-2e43-4000-bc64-973075ca2dd0'
 group by 1
```

**Review by pissac17 — APPROVED** [review]
The data table looks good to me, I don't see any issues.

**Review by dzeber — APPROVED** [review]

**Comment by xluo-ds** [comment]
@alekhyamoz  Dave updated in the team meeting notes "Please backfill from 2023-07-14 onwards"

**Comment by dzeber** [comment]
@alekhyamoz looks like the [first force-push](https://github.com/mozilla/bigquery-etl/compare/a030b3362b21ecd72c007c9286446df7cf440101..8e377ad9e1cec9629e5dc73d71fb0f7a8a4d6e04) clobbered my recent changes. Could you please restore these?

Remaining tasks:

- [ ] Update the table to restore recent changes @alekhyamoz 
- [ ] Backfill the table starting on 2023-07-14 @alekhyamoz 
- [ ] Update Looker so the automated jobs pull this table into Looker @dzeber 
- [ ] Create a basic explore for Jim & document the fields in Looker @dzeber 
- [ ] Update DTMO documentation for this table @dzeber

**Pull request merged**
