### PR TITLE
Add more events to contextual_services.event_aggregates

### PR DESCRIPTION
**Pull request by rebecca-burwei**
A part of https://mozilla-hub.atlassian.net/browse/RS-406

Checklist for reviewer:

- [ ] Commits should reference a bug or github issue, if relevant (if a bug is referenced, the pull request should include the bug number in the title)
- [ ] If the PR comes from a fork, trigger integration CI tests by running the [Push to upstream workflow](https://github.com/mozilla/bigquery-etl/actions/workflows/push-to-upstream.yml) and provide the `<username>:<branch>` of the fork as parameter. The parameter will also show up
in the logs of the `manual-trigger-required-for-fork` CI task together with more detailed instructions.
- [ ] If adding a new field to a query, ensure that the schema and dependent downstream schemas have been updated

For modifications to schemas in restricted namespaces (see [`CODEOWNERS`](/CODEOWNERS)):
- [ ] Follow the [change control procedure](https://docs.google.com/document/d/1TTJi4ht7NuzX6BPG_KTr6omaZg70cEpxe9xlpfnHj9k/edit#heading=h.ttegrcfy18ck)

### CODE REVIEW

**Comment by rebecca-burwei** [comment]
I have attempted to follow the steps described [here](https://mozilla.github.io/bigquery-etl/cookbooks/common_workflows/#add-a-new-field-to-a-table-schema), and did not have permission to run Step 3.

@skahmann3 here's the PR ready for DE support

**Comment by quiiver** [comment]
is this related to https://mozilla-hub.atlassian.net/browse/DENG-317 ?

**Comment by skahmann3** [comment]
@quiiver in working on this query, we found the above issue. This query doesn't appear to be impacted by the impression client counts issue

**Comment by rebecca-burwei** [comment]
Note to self to document this somewhere for DS: 

To get past the permissions problems with step 3, do this:
```
gcloud config set project moz-fx-data-shared-prod 
./bqetl query validate --use-cloud-function=false contextual_services.event_aggregates
```

**Comment by rebecca-burwei** [comment]
We're still on step 3 of the workflow. Ran into a bug. Bug will be fixed by https://github.com/mozilla/bigquery-etl/pull/3168 . Blocked until then.

**Comment by rebecca-burwei** [comment]
Still on step 3. Blocked by https://github.com/mozilla/bigquery-etl/pull/3170

**Comment by rebecca-burwei** [comment]
Stakeholder wants client-level dataset, not aggregated.

**Comment by rebecca-burwei** [comment]
Steps 1-3 [here](https://mozilla.github.io/bigquery-etl/cookbooks/common_workflows/#add-a-new-field-to-a-table-schema) are complete!

What's still needed:

- review from Nan
- DE or DSRE support to finish the rest of the [steps](https://mozilla.github.io/bigquery-etl/cookbooks/common_workflows/#add-a-new-field-to-a-table-schema) because DS does not have permission to update schemas

**Comment by rebecca-burwei** [comment]
@skahmann3 It is up to you and your stakeholders if you want to merge this before or after the [revamp](https://mozilla-hub.atlassian.net/browse/ADPRODUCTS-367). If there is an urgent need for this to be done, then I recommend merging it as soon as you get the green light from Nan and (either DE or DSRE). If there is not an urgent need, I think we can finish the revamp by all hands.

**Pull request closed without merging**
