### PR TITLE
Bug 1712828 Add urlbar_picked keyed scalars to clients_daily

### PR DESCRIPTION
**Pull request by jklukas**
Addresses https://bugzilla.mozilla.org/show_bug.cgi?id=1712828 and also adds the preferences_paneHome keyed scalar from https://bugzilla.mozilla.org/show_bug.cgi?id=1715377

### CODE REVIEW

**Comment by jklukas** [comment]
First commit here is just the changes to the `clients_daily_v6` query itself. I'll be adding additional commits with the results of propagating the schema changes per https://mozilla.github.io/bigquery-etl/cookbooks/common_workflows.html#add-a-new-field-to-clients_daily

**Comment by jklukas** [comment]
Should just need updates to tests at this point. CI is expected to fail until we actually update the schemas in prod.

**Review by scholtzan — APPROVED** [review]

**Comment by scholtzan** [comment]
I think removing the clients_daily_v6 test case is fine

**Comment by jklukas** [comment]
Will rebase on https://github.com/mozilla/bigquery-etl/pull/2117 once that's merged, which removes the failing test case here.

**Comment by rebecca-burwei** [comment]
Hi Jeff, thanks for working on this. For https://bugzilla.mozilla.org/show_bug.cgi?id=1715377  - Will data from this probe be backfilled from the main ping to clients_daily for all the historical main ping data we have, or will we only get data in clients_daily for dates going forward? Either works for me, just curious.

**Comment by jklukas** [comment]
> Will data from this probe be backfilled from the main ping to clients_daily for all the historical main ping data we have, or will we only get data in clients_daily for dates going forward? Either works for me, just curious.

It's not backfilled automatically. That has to be done manually in a separate step after this is merged. I've proposed that we make 60-day backfill a standard when adding fields to clients_daily and downstream, and that is (lightly) documented here: https://docs.telemetry.mozilla.org/cookbooks/clients_last_seen_bits.html#proposing-a-new-bit-pattern-field

In practice, we usually make a one-off decision about it. I'll plan to do a 60-day backfill in this case. I'll likely merge this and backfill on Monday.

**Comment by rebecca-burwei** [comment]
Sounds good - thank you!

**Comment by jklukas** [comment]
This is now deployed and clients_daily backfill is complete for 2021-04-14 to present. `clients_last_seen` backfill will run overnight.

**Pull request merged**
