### PR TITLE
Change Fivetran Airflow operators to run synchronously so the task concurrency limit is respected

### PR DESCRIPTION
**Pull request by sean-rose**
#5083 tried to limit Fivetran task concurrency so it would only run one sync per connector at a time, but that didn't actually work because task concurrency limits apparently don't apply when tasks get deferred (maybe an Airflow bug?).  This will address that.

While having the operator be deferred while waiting for the Fivetran sync to complete would be ideal from an Airflow resource usage perspective, I believe having the sync behavior work as intended is more important, and having the Fivetran operator take up a worker slot while it's waiting shouldn't be a dealbreaker since that was the behavior until very recently when we switched to Astronomer's Fivetran Airflow provider package with its deferrable operator implementation (https://github.com/mozilla/telemetry-airflow/pull/1922, https://github.com/mozilla/bigquery-etl/pull/5080).

Related PR: https://github.com/mozilla/telemetry-airflow/pull/1932

---
Checklist for reviewer:

- [ ] Commits should reference a bug or github issue, if relevant (if a bug is referenced, the pull request should include the bug number in the title).
- [ ] If the PR comes from a fork, trigger integration CI tests by running the [Push to upstream workflow](https://github.com/mozilla/bigquery-etl/actions/workflows/push-to-upstream.yml) and provide the `<username>:<branch>` of the fork as parameter. The parameter will also show up
in the logs of the `manual-trigger-required-for-fork` CI task together with more detailed instructions.
- [ ] If adding a new field to a query, ensure that the schema and dependent downstream schemas have been updated.
- [ ] When adding a new derived dataset, ensure that data is not available already (fully or partially) and recommend extending an existing dataset in favor of creating new ones. Data can be available in the [bigquery-etl repository](https://github.com/mozilla/bigquery-etl), [looker-hub](https://github.com/mozilla/looker-hub) or in [looker-spoke-default](https://github.com/mozilla/looker-spoke-default/tree/e1315853507fc1ac6e78d252d53dc8df5f5f322b).

For modifications to schemas in restricted namespaces (see [`CODEOWNERS`](https://github.com/mozilla/bigquery-etl/blob/main/CODEOWNERS)):
- [ ] Follow the [change control procedure](https://docs.google.com/document/d/1TTJi4ht7NuzX6BPG_KTr6omaZg70cEpxe9xlpfnHj9k/edit#heading=h.ttegrcfy18ck)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2925)

### CODE REVIEW

**Review by BenWu — COMMENTED** [review]
Out of curiosity, I took a look at how the `deferrable` arg is implemented and it look like it just runs the sleep function instead of doing a typical sensor operator poke since it's not a sensor operator. https://github.com/astronomer/airflow-provider-fivetran-async/blob/main/fivetran_provider_async/operators.py#L133
I think this means it will actually take up a slot during the entire wait.  Do you know if this is actually the case?  And how long do these typically wait for?

**Comment by BenWu** [comment]
This might be a non-issue, especially if the syncs don't take that long.  It's just that I was under the impression that it would behave like a regular sensor and taking up slots waiting might stall other tasks.  Another option is to use the FivetranSensor which I believe we were previously using.

**Comment by sean-rose** [comment]
> Out of curiosity, I took a look at how the `deferrable` arg is implemented and it look like it just runs the sleep function instead of doing a typical sensor operator poke since it's not a sensor operator. https://github.com/astronomer/airflow-provider-fivetran-async/blob/main/fivetran_provider_async/operators.py#L133 I think this means it will actually take up a slot during the entire wait. Do you know if this is actually the case? 

Yep, in non-deferrable mode it'll take up a worker slot the whole time it's running, but so do sensors in the default `poke` mode (as opposed to `reschedule`), which is how the Fivetran sensors were running prior to mozilla/telemetry-airflow#1922 + #5080.  So it's definitely not ideal, but is basically a return to the previous status quo regarding Fivetran tasks taking up worker slots (ideal would be having some way to control the concurrency of deferred task instances for the same task so we could run these in deferrable mode).

> And how long do these typically wait for?

It probably varies widely depending on the data source.  The Fivetran connector I'm most familiar with is Stripe, which typically takes less than 30 minutes, but could easily take much longer if a historical resync is happening or the Stripe API is being slow.

**Comment by sean-rose** [comment]
> Another option is to use the FivetranSensor which I believe we were previously using.

I wouldn't want to return to using a separate sensor, because then we wouldn't be able to control the concurrency of when it tries to start Fivetran syncs since the start task completes immediately.

**Review by BenWu — APPROVED** [review]
Oh right, reschedule is the word I was thinking of.  I thought we were doing that with fivetran before but if it worked before then I have no problem returning to that.  I don't think this is a big issue, just want to make sure we understand the behaviour.

And not using the sensor makes sense to me as well

**Pull request merged**
