### PR TITLE
[MRG] Remove `urlbar_clients_daily`

### PR DESCRIPTION
**Pull request by teonbrooks**
This is PR is to start a discussion, and define the steps needed to decommission an unused data table `urlbar_clients_daily`. 

This is table has fallen out of favor with the creation of glean event `urlbar` and its derived table `urlbar_events`. The new table `urlbar_events` has a complete representation of the information that `urlbar_clients_daily` used to provide with several advantages.
1. `urlbar_events` uses Glean for its data collection whereas `urlbar_clients_daily` uses a combination of scalars and prefs from `clients_daily` to represent the same information. 
2. The new event table also includes additional logic such as where an event was abandoned or an annoyance. It also captures more information about the urlbar and the options presented to users.
3. The `urlbar_clients_daily` table is also not powering any new analyses and it delineates from our goal of having one SSOT.

Checklist for reviewer:

- [ ] Commits should reference a bug or github issue, if relevant (if a bug is referenced, the pull request should include the bug number in the title).
- [ ] If the PR comes from a fork, trigger integration CI tests by running the [Push to upstream workflow](https://github.com/mozilla/bigquery-etl/actions/workflows/push-to-upstream.yml) and provide the `<username>:<branch>` of the fork as parameter. The parameter will also show up
in the logs of the `manual-trigger-required-for-fork` CI task together with more detailed instructions.
- [ ] If adding a new field to a query, ensure that the schema and dependent downstream schemas have been updated.
- [ ] When adding a new derived dataset, ensure that data is not available already (fully or partially) and recommend extending an existing dataset in favor of creating new ones. Data can be available in the [bigquery-etl repository](https://github.com/mozilla/bigquery-etl), [looker-hub](https://github.com/mozilla/looker-hub) or in [looker-spoke-default](https://github.com/mozilla/looker-spoke-default/tree/e1315853507fc1ac6e78d252d53dc8df5f5f322b).

For modifications to schemas in restricted namespaces (see [`CODEOWNERS`](https://github.com/mozilla/bigquery-etl/blob/main/CODEOWNERS)):
- [ ] Follow the [change control procedure](https://docs.google.com/document/d/1TTJi4ht7NuzX6BPG_KTr6omaZg70cEpxe9xlpfnHj9k/edit#heading=h.ttegrcfy18ck)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2568)

### CODE REVIEW

**Review by dzeber — COMMENTED** [review]
LGTM - AFAIK data science is no longer using the Legacy telemetry measurements made available in this table.

Not sure what other steps are required to decommission the table, eg. removing the task from the DAG. Also, I'm not sure if anything else is built on top of this table that people still use. [Looks like](https://mozilla.acryl.io/dataset/urn:li:dataset:(urn:li:dataPlatform:bigquery,mozdata.telemetry.urlbar_clients_daily,PROD)/Lineage?filter_degree___false___EQUAL___0=2,1,3%2B&is_lineage_mode=false&page=1&unionType=0) there is a Looker view as well as a couple of dashboards.

**Comment by teonbrooks** [comment]
@alekhyamoz is there anything else I should do here? I am also happy to hand this over to you if you would like to handle this process

**Comment by alekhyamoz** [comment]
@teonbrooks  as long as you can confirm that none of the downstream tables or Looker dashboards are dependent on this. I can kick off the process.

**Comment by alekhyamoz** [comment]
I have created a Jira ticket to track the process - https://mozilla-hub.atlassian.net/browse/DENG-2770

**Comment by teonbrooks** [comment]
> @teonbrooks as long as you can confirm that none of the downstream tables or Looker dashboards are dependent on this. I can kick off the process.

i can confirm. the only dashboards connected to it have already been marked for deletion and archived or marked as abandoned all in 2023.

**Comment by alekhyamoz** [comment]
@teonbrooks closing this PR place of https://github.com/mozilla/bigquery-etl/pull/5046

**Pull request closed without merging**
