### PR TITLE
Remove old histogram from devtools_panel_usage_v1

### PR DESCRIPTION
**Pull request by relud**
and format_sql
fixes https://circleci.com/gh/mozilla/bigquery-etl/9040

### CODE REVIEW

**Comment by jklukas** [comment]
What histogram was removed? The diff here is not really helpful since it's dominated by formatting changes.

**Comment by jklukas** [comment]
I see now the linked error shows `histogram_parent_devtools_developertoolbar_opened_count_sum`. This field was removed from `clients_daily`?

**Comment by relud** [comment]
> What histogram was removed? The diff here is not really helpful since it's dominated by formatting changes.

I split it into two commits, https://github.com/mozilla/bigquery-etl/pull/705/commits/016166da744454bfdb26f61e93142fb62809a152 shows the removal of `histogram_parent_devtools_developertoolbar_opened_count_sum`

> This field was removed from `clients_daily`?

it was removed from the view in #688, and it's `NULL` in [clients_daily_v6/query.sql#160](https://github.com/mozilla/bigquery-etl/blob/master/templates/telemetry_derived/clients_daily_v6/query.sql#L160)

**Comment by jklukas** [comment]
I reran the task for today and it succeeded.

**Pull request merged**
