### PR TITLE
trim whitespace

### PR DESCRIPTION
**Pull request by Marlene-M-Hirose**
Checklist for reviewer:

- [x] Commits should reference a bug or github issue, if relevant (if a bug is referenced, the pull request should include the bug number in the title)
- [x] If the PR comes from a fork, trigger integration CI tests by running the [Push to upstream workflow](https://github.com/mozilla/bigquery-etl/actions/workflows/push-to-upstream.yml) and provide the `<username>:<branch>` of the fork as parameter. The parameter will also show up
in the logs of the `manual-trigger-required-for-fork` CI task together with more detailed instructions.
- [ ] If adding a new field to a query, ensure that the schema and dependent downstream schemas have been updated

For modifications to schemas in restricted namespaces (see [`CODEOWNERS`](/CODEOWNERS)):
- [ ] Follow the [change control procedure](https://docs.google.com/document/d/1TTJi4ht7NuzX6BPG_KTr6omaZg70cEpxe9xlpfnHj9k/edit#heading=h.ttegrcfy18ck)

### CODE REVIEW

**Comment by Marlene-M-Hirose** [comment]
@irrationalagent I'm updating the unified metrics table's Firefox iOS is_default_browser to deal with the update in version 14 where we could see if default_browser was set to ON

**Comment by irrationalagent** [comment]
@Marlene-M-Hirose What is the reasoning here for why we aren't changing the `is_default_browser` field directly in `firefox_ios.clients_last_seen_joined`? 

My concern is that if we change the behavior here but not there, then that could lead to confusion about why the two tables don't align

**Comment by Marlene-M-Hirose** [comment]
> 

@irrationalagent That makes sense.  Lucia and I thought this was a good place to make the changes. Though, I did think it would be make the query more complex than needed.

@lucia-vargas-a , it seems like it is better to make the changes in the firefox_ios.clients_last_seen_joined as Leif suggests. What do you think?

**Comment by lucia-vargas-a** [comment]
Sure I agree that data needs to be consistent!
My reasoning behind recommending adding it to unified_metrics is because I understood this case as marketing-specific logic that could be applied here in a similar way as we find [user segments](https://github.com/mozilla/bigquery-etl/blob/5f1a04335c0d94ff5c5caeb405a2aeeb8b9bee98/sql/moz-fx-data-shared-prod/telemetry_derived/unified_metrics_v1/query.sql#L195), so I'd check if there is inconsistency with the upstream and if the logic applies overall.

Btw, didn't we get this potential difference in the health checks or user validation on the analysis dataset?

**Comment by Marlene-M-Hirose** [comment]
> Btw, didn't we get this potential difference in the health checks or user validation on the analysis dataset?

I think we did.

**Pull request closed without merging**
