### PR TITLE
Use the UDF's actual name as the directory name

### PR DESCRIPTION
**Pull request by badboy**
That way the generated docs also end up using the correct full name
(`fenix_build_to_datetime`).

---

Checklist for reviewer:

- [ ] Commits should reference a bug or github issue, if relevant (if a bug is referenced, the pull request should include the bug number in the title)
- [ ] If the PR comes from a fork, trigger integration CI tests by running the [Push to upstream workflow](https://github.com/mozilla/bigquery-etl/actions/workflows/push-to-upstream.yml) and provide the `<username>:<branch>` of the fork as parameter. The parameter will also show up
in the logs of the `manual-trigger-required-for-fork` CI task together with more detailed instructions.
- [ ] If adding a new field to a query, ensure that the schema and dependent downstream schemas have been updated

For modifications to schemas in restricted namespaces (see [`CODEOWNERS`](/CODEOWNERS)):
- [ ] Follow the [change control procedure](https://docs.google.com/document/d/1TTJi4ht7NuzX6BPG_KTr6omaZg70cEpxe9xlpfnHj9k/edit#heading=h.ttegrcfy18ck)

### CODE REVIEW

**Comment by badboy** [comment]
https://github.com/mozilla/bigquery-etl/commit/45ab9cd828c5f9b20823caa598536b3eada12a67#commitcomment-82505504

### Integration report for "Use the UDF's actual name as the directory name"
#### `sql.diff`
<details>
<summary>Click to expand!</summary>

```diff
Only in bigquery-etl-main/sql/mozfun/norm: fenix_build_to_date
Only in /tmp/workspace/generated-sql/sql/mozfun/norm: fenix_build_to_datetime

```

</details>

---

not sure how to interpret that and whether that's a breaking thing.

**Review by kik-kik — APPROVED** [review]
Seems fine to me since the UDF definition already uses this as the actual udf name so no sql changes required. Not quite sure why the dir name was different to begin with.

**Comment by kik-kik** [comment]
@badboy can we merge this?

**Comment by badboy** [comment]
> @badboy can we merge this?

Yes, please. I didn't do that on my own as I don't own this repo (even though I have enough rights to do so)

**Pull request merged**
