### PR TITLE
Bug 1852630 - Rename main_remainder_v4 to main_v5

### PR DESCRIPTION
**Pull request by relud**
and point at new copy_deduplicate tasks for similar pings

[Bug 1852630](https://bugzilla.mozilla.org/show_bug.cgi?id=1852630)
requires https://github.com/mozilla/telemetry-airflow/pull/1825

Checklist for reviewer:

- [ ] Commits should reference a bug or github issue, if relevant (if a bug is referenced, the pull request should include the bug number in the title).
- [ ] If the PR comes from a fork, trigger integration CI tests by running the [Push to upstream workflow](https://github.com/mozilla/bigquery-etl/actions/workflows/push-to-upstream.yml) and provide the `<username>:<branch>` of the fork as parameter. The parameter will also show up
in the logs of the `manual-trigger-required-for-fork` CI task together with more detailed instructions.
- [ ] If adding a new field to a query, ensure that the schema and dependent downstream schemas have been updated.
- [ ] When adding a new derived dataset, ensure that data is not available already (fully or partially) and recommend extending an existing dataset in favor of creating new ones. Data can be available in the [bigquery-etl repository](https://github.com/mozilla/bigquery-etl), [looker-hub](https://github.com/mozilla/looker-hub) or in [looker-spoke-default](https://github.com/mozilla/looker-spoke-default/tree/e1315853507fc1ac6e78d252d53dc8df5f5f322b).

For modifications to schemas in restricted namespaces (see [`CODEOWNERS`](https://github.com/mozilla/bigquery-etl/blob/main/CODEOWNERS)):
- [ ] Follow the [change control procedure](https://docs.google.com/document/d/1TTJi4ht7NuzX6BPG_KTr6omaZg70cEpxe9xlpfnHj9k/edit#heading=h.ttegrcfy18ck)

### CODE REVIEW

**Review by akkomar — APPROVED** [review]
Discussed on Slack, there's a bunch of other places where main_remainder_v4 is used: https://github.com/search?q=repo%3Amozilla%2Fbigquery-etl%20main_remainder_v4&type=code

**Comment by whd** [comment]
> Discussed on Slack, there's a bunch of other places where main_remainder_v4 is used: https://github.com/search?q=repo%3Amozilla%2Fbigquery-etl%20main_remainder_v4&type=code

We'll hold off on step 12 of https://bugzilla.mozilla.org/show_bug.cgi?id=1852630#c7 until these references are all updated.

**Comment by relud** [comment]
> > Discussed on Slack, there's a bunch of other places where main_remainder_v4 is used: https://github.com/search?q=repo%3Amozilla%2Fbigquery-etl%20main_remainder_v4&type=code
> 
> We'll hold off on step 12 of https://bugzilla.mozilla.org/show_bug.cgi?id=1852630#c7 until these references are all updated.

these references are updated in https://github.com/mozilla/bigquery-etl/pull/4276

**Comment by relud** [comment]
added this to https://github.com/mozilla/bigquery-etl/pull/4276

**Pull request merged**
