### PR TITLE
bug(1741487): Rename url2 and related fields in stable views

### PR DESCRIPTION
**Pull request by kik-kik**
# bug(1741487): Rename url2 and related fields in stable views

---

Apologies for the whole mix up with PR's, decided it's best to recreate it with the original commits.

---

Opened a new PR as the previously open one was having some issues and was showing a mass of changes that were unrelated to the changes made in this branch (original PR: https://github.com/mozilla/bigquery-etl/pull/3955). 

The diff shown by Github started showing a lot more changes after attempting to rebase the branch on main after a few weeks of inactivity. This is why a new PR was opened without all the noise.

Affected fields:

- `jwe`
- `text`
- `url`
- `labeled_rate`

The changes include:

- Adding detailed comments for why the we added this custom logic for excluding and aliasing the fields.
- Excluding all of the affected fields (listed above) if they exist in the table.
- Aliasing any of the corresponding fields with a suffix 2 to not include the suffix in the field name.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1125)

### CODE REVIEW

**Comment by kik-kik** [comment]
Here's some samples from the diff (main vs this branch generated files):

```
diff --color -r old_generated_sql/moz-fx-data-shared-prod/org_mozilla_vrbrowser/sync/schema.yaml new_generated_sql/moz-fx-data-shared-prod/org_mozilla_vrbrowser/sync/schema.yaml
355,408d354
<   - name: jwe
<     type: RECORD
<     mode: REPEATED
<     fields:
<     - name: key
<       type: STRING
<       mode: NULLABLE
<     - name: value
<       type: STRING
<       mode: NULLABLE
<   - name: labeled_rate
<     type: RECORD
<     mode: REPEATED
<     fields:
<     - name: key
<       type: STRING
<       mode: NULLABLE
<     - name: value
<       type: RECORD
<       mode: REPEATED
<       fields:
<       - name: key
<         type: STRING
<         mode: NULLABLE
<       - name: value
<         type: RECORD
<         mode: NULLABLE
<         fields:
<         - name: denominator
<           type: INTEGER
<           mode: NULLABLE
<         - name: numerator
<           type: INTEGER
<           mode: NULLABLE
<   - name: url
<     type: RECORD
<     mode: REPEATED
<     fields:
<     - name: key
<       type: STRING
<       mode: NULLABLE
<     - name: value
<       type: STRING
<       mode: NULLABLE
<   - name: text
<     type: RECORD
<     mode: REPEATED
<     fields:
<     - name: key
<       type: STRING
<       mode: NULLABLE
<     - name: value
<       type: STRING
<       mode: NULLABLE
diff --color -r old_generated_sql/moz-fx-data-shared-prod/org_mozilla_vrbrowser/sync/view.sql new_generated_sql/moz-fx-data-shared-prod/org_mozilla_vrbrowser/sync/view.sql
8c8,9
<     mozfun.norm.glean_ping_info(ping_info) AS ping_info
---
>     mozfun.norm.glean_ping_info(ping_info) AS ping_info,
>     (SELECT AS STRUCT metrics.* EXCEPT (jwe, labeled_rate, text, url)) AS metrics
```

---

```
diff --color -r old_generated_sql/moz-fx-data-shared-prod/pine/metrics/schema.yaml new_generated_sql/moz-fx-data-shared-prod/pine/metrics/schema.yaml
3452a3453,3462
>   - name: url
>     type: RECORD
>     mode: NULLABLE
>     fields:
>     - name: search_engine_default_submission_url
>       type: STRING
>       mode: NULLABLE
>     - name: search_engine_private_submission_url
>       type: STRING
>       mode: NULLABLE
diff --color -r old_generated_sql/moz-fx-data-shared-prod/pine/metrics/view.sql new_generated_sql/moz-fx-data-shared-prod/pine/metrics/view.sql
38c38,39
<         )
---
>         ),
>         metrics.url2 AS url
```

---

```
diff --color -r old_generated_sql/moz-fx-data-shared-prod/viu_politica/video_data/schema.yaml new_generated_sql/moz-fx-data-shared-prod/viu_politica/video_data/schema.yaml
350a351,357
>   - name: text
>     type: RECORD
>     mode: NULLABLE
>     fields:
>     - name: video_data_description
>       type: STRING
>       mode: NULLABLE
diff --color -r old_generated_sql/moz-fx-data-shared-prod/viu_politica/video_data/view.sql new_generated_sql/moz-fx-data-shared-prod/viu_politica/video_data/view.sql
8c8,9
<     mozfun.norm.glean_ping_info(ping_info) AS ping_info
---
>     mozfun.norm.glean_ping_info(ping_info) AS ping_info,
>     (SELECT AS STRUCT metrics.*, metrics.text2 AS text) AS metrics
```

---

```
diff --color -r old_generated_sql/moz-fx-data-shared-prod/org_mozilla_vrbrowser/tabs_sync/schema.yaml new_generated_sql/moz-fx-data-shared-prod/org_mozilla_vrbrowser/tabs_sync/schema.yaml
295,304d294
<   - name: jwe
<     type: RECORD
<     mode: REPEATED
<     fields:
<     - name: key
<       type: STRING
<       mode: NULLABLE
<     - name: value
<       type: STRING
<       mode: NULLABLE
433,456d422
<   - name: labeled_rate
<     type: RECORD
<     mode: REPEATED
<     fields:
<     - name: key
<       type: STRING
<       mode: NULLABLE
<     - name: value
<       type: RECORD
<       mode: REPEATED
<       fields:
<       - name: key
<         type: STRING
<         mode: NULLABLE
<       - name: value
<         type: RECORD
<         mode: NULLABLE
<         fields:
<         - name: denominator
<           type: INTEGER
<           mode: NULLABLE
<         - name: numerator
<           type: INTEGER
<           mode: NULLABLE
507,526d472
<   - name: url
<     type: RECORD
<     mode: REPEATED
<     fields:
<     - name: key
<       type: STRING
<       mode: NULLABLE
<     - name: value
<       type: STRING
<       mode: NULLABLE
<   - name: text
<     type: RECORD
<     mode: REPEATED
<     fields:
<     - name: key
<       type: STRING
<       mode: NULLABLE
<     - name: value
<       type: STRING
<       mode: NULLABLE
diff --color -r old_generated_sql/moz-fx-data-shared-prod/org_mozilla_vrbrowser/tabs_sync/view.sql new_generated_sql/moz-fx-data-shared-prod/org_mozilla_vrbrowser/tabs_sync/view.sql
11c11
<         metrics.* REPLACE (
---
>         metrics.* EXCEPT (jwe, labeled_rate, text, url) REPLACE(
```

**Review by scholtzan — APPROVED** [review]
This looks good to me. The stage deploy is failing because all (?) the stable views seem to have changed which requires all stable tables to be deployed

**Comment by kik-kik** [comment]
@scholtzan does that mean you're happy for us to get this merged? We might need admin intervention to merge this PR due to `validate_metadata` not being able to complete as it will not run until `ci/circleci: deploy-changes-to-stage` passes

**Comment by scholtzan** [comment]
Yeah, a repo Admin can merge this ignoring CI failures

**Pull request merged**
