### PR TITLE
Move to python 3.10

### PR DESCRIPTION
**Pull request by fbertsch**
Checklist for reviewer:

- [ ] Commits should reference a bug or github issue, if relevant (if a bug is referenced, the pull request should include the bug number in the title)
- [ ] If the PR comes from a fork, trigger integration CI tests by running the [Push to upstream workflow](https://github.com/mozilla/bigquery-etl/actions/workflows/push-to-upstream.yml) and provide the `<username>:<branch>` of the fork as parameter. The parameter will also show up
in the logs of the `manual-trigger-required-for-fork` CI task together with more detailed instructions.
- [ ] If adding a new field to a query, ensure that the schema and dependent downstream schemas have been updated

For modifications to schemas in restricted namespaces (see [`CODEOWNERS`](/CODEOWNERS)):
- [ ] Follow the [change control procedure](https://docs.google.com/document/d/1TTJi4ht7NuzX6BPG_KTr6omaZg70cEpxe9xlpfnHj9k/edit#heading=h.ttegrcfy18ck)

### CODE REVIEW

**Comment by sean-rose** [comment]
This was previously tried by @relud in August: #3155

**Review by relud — APPROVED** [review]

**Comment by fbertsch** [comment]
The Netlify build is still present, but passing. I'm wondering if there's another config I need to change, or if they will stop when this hits main (I tried logging in to Netlify but there wasn't anything available to me)

**Comment by relud** [comment]
I think there might be a part that DSRE needs to disconnect, cc @cmharlow

**Comment by sean-rose** [comment]
Some additional places to update with Python 3.10:
- [.circleci/config.yml](https://github.com/mozilla/bigquery-etl/blob/00a04b699c6899bd5657e0d70c7147c70a9eb650/.circleci/config.yml#L16-L35)
- [bqetl](https://github.com/mozilla/bigquery-etl/blob/00a04b699c6899bd5657e0d70c7147c70a9eb650/bqetl#L15)
- Might need to recompile [requirements.txt](https://github.com/mozilla/bigquery-etl/blob/00a04b699c6899bd5657e0d70c7147c70a9eb650/requirements.txt#L2)?

**Pull request merged**
