### PR TITLE
Have Glean stable views parse datetime metrics as timestamps (bug 1771733)

### PR DESCRIPTION
**Pull request by sean-rose**
## [Bug 1771733](https://bugzilla.mozilla.org/show_bug.cgi?id=1771733): Map Glean 'datetime' type to a 'datetime' in bigquery views

Datetime metrics are stored in BigQuery tables as strings, which is not very user friendly.  This will change the generated stable views to replace those string fields with timestamp fields, while still providing the original string values in fields prefixed with `raw_`.  For example, a `metrics.datetime.foo` string field would be replaced with a timestamp field, and the string value would be available in an additional `metrics.datetime.raw_foo` field.

Note that despite the title of the bug, we're parsing the datetime metrics as _timestamps_ to preserve their accuracy in representing an exact point in time.  However, all BigQuery timestamps are inherently in UTC, so the original time zone isn't readily available, but could be retrieved from the original string value if needed.

---
Checklist for reviewer:

- [ ] Commits should reference a bug or github issue, if relevant (if a bug is referenced, the pull request should include the bug number in the title).
- [ ] If the PR comes from a fork, trigger integration CI tests by running the [Push to upstream workflow](https://github.com/mozilla/bigquery-etl/actions/workflows/push-to-upstream.yml) and provide the `<username>:<branch>` of the fork as parameter. The parameter will also show up
in the logs of the `manual-trigger-required-for-fork` CI task together with more detailed instructions.
- [ ] If adding a new field to a query, ensure that the schema and dependent downstream schemas have been updated.
- [ ] When adding a new derived dataset, ensure that data is not available already (fully or partially) and recommend extending an existing dataset in favor of creating new ones. Data can be available in the [bigquery-etl repository](https://github.com/mozilla/bigquery-etl), [looker-hub](https://github.com/mozilla/looker-hub) or in [looker-spoke-default](https://github.com/mozilla/looker-spoke-default/tree/e1315853507fc1ac6e78d252d53dc8df5f5f322b).

For modifications to schemas in restricted namespaces (see [`CODEOWNERS`](/CODEOWNERS)):
- [ ] Follow the [change control procedure](https://docs.google.com/document/d/1TTJi4ht7NuzX6BPG_KTr6omaZg70cEpxe9xlpfnHj9k/edit#heading=h.ttegrcfy18ck)

### CODE REVIEW

**Comment by sean-rose** [comment]
Still TBD:
- Whether there are any downstream impacts (e.g. ETLs, Looker).
- Whether a special deployment process is needed given that this introduces and relies on a new UDF.
  - Maybe the fact that it's referenced in generated SQL rather than checked in SQL means the CI/deployment won't choke on the UDF not already existing?

**Comment by badboy** [comment]
Thanks for this! I was still dealing with understanding a bit more about bigquery-etl before I would have achieved at a solution.

**Comment by sean-rose** [comment]
> Still TBD:
> * Whether there are any downstream impacts (e.g. ETLs, Looker).

As best I can tell from searching the code in [bigquery-etl](https://github.com/mozilla/bigquery-etl/tree/generated-sql), [looker-hub](https://github.com/mozilla/looker-hub), and [looker-spoke-default](https://github.com/mozilla/looker-spoke-default) no datetime metrics are currently being used in ETLs or Looker (at least Looker content that's saved in GitHub).

**Review by scholtzan — APPROVED** [review]

**Comment by sean-rose** [comment]
> > Still TBD:
> > 
> > * Whether there are any downstream impacts (e.g. ETLs, Looker).
> 
> As best I can tell from searching the code in [bigquery-etl](https://github.com/mozilla/bigquery-etl/tree/generated-sql), [looker-hub](https://github.com/mozilla/looker-hub), and [looker-spoke-default](https://github.com/mozilla/looker-spoke-default) no datetime metrics are currently being used in ETLs or Looker (at least Looker content that's saved in GitHub).

Since not all Looker content is saved in GitHub I looked at the `mozdata` BigQuery project's query history for the last month and only found two instances of reporting queries referencing datetime metrics:
- Nov 15: a couple of Looker queries on `fenix.addresses_sync` and `fenix.bookmarks_sync` by Looker user ID 777.
- Nov 10: a series of Redash queries on `firefox_ios.baseline` by @badboy that ended up saved as [STMO query 88603](https://sql.telemetry.mozilla.org/queries/88603/source), but which is now archived.

Based on that I feel fairly confident this change won't break existing reporting, and will proceed with posting a PSA in the [#data](https://mozilla.slack.com/archives/CKFKC7Y1Y) channel and then merge this ~24 hours later.

**Comment by sean-rose** [comment]
> Still TBD:
>   * Whether a special deployment process is needed given that this introduces and relies on a new UDF.
>     * Maybe the fact that it's referenced in generated SQL rather than checked in SQL means the CI/deployment won't choke on the UDF not already existing?

It turns out that although the `generate-sql` CI step is considered passing, it's actually failing to generate `schema.yaml` files for the affected views because dry-running the view SQL fails due to the `mozfun.glean.parse_datetime` UDF not existing yet.

Therefore my plan is to manually create the `mozfun.glean.parse_datetime` UDF just prior to merging this PR so the SQL generation and views deployment will succeed when it's merged.

**Pull request merged**
