### PR TITLE
add "channel" as a dimension in search_aggregates

### PR DESCRIPTION
**Pull request by xluo-ds**
Checklist for reviewer:

- [ ] Commits should reference a bug or github issue, if relevant (if a bug is referenced, the pull request should include the bug number in the title)
- [ ] If the PR comes from a fork, trigger integration CI tests by running the [Push to upstream workflow](https://github.com/mozilla/bigquery-etl/actions/workflows/push-to-upstream.yml) and provide the `<username>:<branch>` of the fork as parameter. The parameter will also show up
in the logs of the `manual-trigger-required-for-fork` CI task together with more detailed instructions.
- [ ] If adding a new field to a query, ensure that the schema and dependent downstream schemas have been updated

### CODE REVIEW

**Review by akkomar — APPROVED** [review]

**Review by wlach — APPROVED** [review]

**Comment by wlach** [comment]
We will want to backfill the historical data. I'm embarrassed to say I don't know the current best practice for this, do you @akkomar?

**Comment by jklukas** [comment]
For backfills over long time periods, running `bqetl query backfill` locally is easier than backfilling via Airflow. If the backfill takes days to run (which is usually only the case for large non-parallelizable depends_on_past queries like clients_last_seen), then it may be necessary to set up a tiny GCE instance for stability.

**Comment by akkomar** [comment]
Yeah, I've been either using cli or just clearing a task in AIrflow.

Do we want to backfill this though? If so, how far back? IIRC this table starts >4 years ago.

**Comment by wlach** [comment]
IME we generally backfill these types of changes to `search_aggregates` as far back as they'll go.

**Comment by akkomar** [comment]
I have backfilled search_aggregates_v8.

**Pull request merged**
