### PR TITLE
[DS-2566] Add sidebar search probes to clients_daily tables

### PR DESCRIPTION
**Pull request by m-d-bowerman**
Adds the probes referenced in [DS-2566](https://mozilla-hub.atlassian.net/browse/DS-2566) for history sidebar searches to clients_daily.

Checklist for reviewer:

- [ ] Commits should reference a bug or github issue, if relevant (if a bug is referenced, the pull request should include the bug number in the title).
- [ ] If the PR comes from a fork, trigger integration CI tests by running the [Push to upstream workflow](https://github.com/mozilla/bigquery-etl/actions/workflows/push-to-upstream.yml) and provide the `<username>:<branch>` of the fork as parameter. The parameter will also show up
in the logs of the `manual-trigger-required-for-fork` CI task together with more detailed instructions.
- [ ] If adding a new field to a query, ensure that the schema and dependent downstream schemas have been updated.
- [ ] When adding a new derived dataset, ensure that data is not available already (fully or partially) and recommend extending an existing dataset in favor of creating new ones. Data can be available in the [bigquery-etl repository](https://github.com/mozilla/bigquery-etl), [looker-hub](https://github.com/mozilla/looker-hub) or in [looker-spoke-default](https://github.com/mozilla/looker-spoke-default/tree/e1315853507fc1ac6e78d252d53dc8df5f5f322b).

For modifications to schemas in restricted namespaces (see [`CODEOWNERS`](https://github.com/mozilla/bigquery-etl/blob/main/CODEOWNERS)):
- [ ] Follow the [change control procedure](https://docs.google.com/document/d/1TTJi4ht7NuzX6BPG_KTr6omaZg70cEpxe9xlpfnHj9k/edit#heading=h.ttegrcfy18ck)

[DS-2566]: https://mozilla-hub.atlassian.net/browse/DS-2566?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by gleonard-m** [comment]
When updating clients_daily we need to update downstream tables as well. Unfortunately, the automatic updates for those are broken because of the query timing out during dry runs.

1. sql/moz-fx-data-shared-prod/telemetry_derived/clients_daily_joined_v1/schema.yaml  
2.   Running `./bqetl query schema update telemetry_derived.clients_daily_v6 --update_downstream` will update that schema for you.
3. sql/moz-fx-data-shared-prod/telemetry_derived/clients_first_seen_v1/schema.yaml (manual update)
4. sql/moz-fx-data-shared-prod/telemetry_derived/clients_last_seen_joined_v1/schema.yaml (manual update)
5. sql/moz-fx-data-shared-prod/telemetry_derived/clients_last_seen_v1/schema.yaml  (manual update)

@scholtzan  I think this covers the additional file updates?

**Comment by m-d-bowerman** [comment]
I've manually updated the downstream tables in the last commit. Strangely, running `./bqetl query schema update telemetry_derived.clients_daily_v6 --update_downstream` didn't update the `clients_daily_joined_v1` schema; the command only attempted to update the `clients_daily_v6` schema.

**Comment by scholtzan** [comment]
you might need to apply some force to update it: `./bqetl query schema update telemetry_derived.clients_daily_v6 --update_downstream --force`

**Review by gleonard-m — APPROVED** [review]
Looks good

**Pull request merged**
