### PR TITLE
Bug 1757768: add match_type to contextual services derived dataset

### PR DESCRIPTION
**Pull request by ncloudioj**
Checklist for reviewer:

- [ ] Commits should reference a bug or github issue, if relevant (if a bug is referenced, the pull request should include the bug number in the title)
- [ ] If the PR comes from a fork, trigger integration CI tests by running the [Push to upstream workflow](https://github.com/mozilla/bigquery-etl/actions/workflows/push-to-upstream.yml) and provide the `<username>:<branch>` of the fork as parameter. The parameter will also show up
in the logs of the `manual-trigger-required-for-fork` CI task together with more detailed instructions.
- [ ] If adding a new field to a query, ensure that the schema and dependent downstream schemas have been updated

For modifications to schemas in restricted namespaces (see [`CODEOWNERS`](/CODEOWNERS)):
- [ ] Follow the [change control procedure](https://docs.google.com/document/d/1TTJi4ht7NuzX6BPG_KTr6omaZg70cEpxe9xlpfnHj9k/edit#heading=h.ttegrcfy18ck)

r? @jklukas @rebecca-burwei

### CODE REVIEW

**Comment by rebecca-burwei** [comment]
thanks Nan! lgtm

**Review by jklukas — APPROVED** [review]

**Comment by rebecca-burwei** [comment]
@ncloudioj @jklukas @whd Can we try to get this PR merged and the data backfilled before Tuesday, June 7?

**Comment by ncloudioj** [comment]
Ok, Mark approved [it](https://mozilla-hub.atlassian.net/browse/DSRE-694). This is now ready to merge. 

cc: @jklukas @whd

**Comment by jklukas** [comment]
I've triggered full CI with credentials on this PR. @whd will need to approve and merge.

**Review by whd — APPROVED** [review]

**Pull request merged**
