### PR TITLE
Remove views on top of sync derived data

### PR DESCRIPTION
**Pull request by jklukas**
We will be deleting the underlying tables.
See https://bugzilla.mozilla.org/show_bug.cgi?id=1612541

### CODE REVIEW

**Comment by jklukas** [comment]
Announced to users in https://groups.google.com/a/mozilla.com/d/msg/fx-data-platform/h4r0nReRFqk/Fe_bRwRGAwAJ

**Comment by whd** [comment]
We should merge this today since I'm seeing`google.api_core.exceptions.NotFound: 404 Not found: Table moz-fx-data-shared-prod:telemetry_derived.sync_flat_summary_v1 was not found in location US` when deploying views updates.

**Comment by jklukas** [comment]
> We should merge this today since I'm seeing`google.api_core.exceptions.NotFound: 404 Not found: Table moz-fx-data-shared-prod:telemetry_derived.sync_flat_summary_v1 was not found in location US` when deploying views updates.

I went ahead and deleted the shared-prod versions of the tables yesterday. I had forgotten that the views had already been changed. Sorry for gumming up deploys.

**Comment by jklukas** [comment]
I've also now manually deleted these views in both projects.

**Pull request merged**
