### PR TITLE
Update glam-fenix etl with static combinations

### PR DESCRIPTION
**Pull request by acmiyaguchi**
This depends on #912. 

TODO: compare number of rows between heads of previous and current PR.

### CODE REVIEW

**Comment by acmiyaguchi** [comment]
@emtwo I've updated the queries to take advantage of the static combination trick that was used in the desktop histogram probe counts query. Do you think it's prudent to also merge the bucket counts and probe counts queries here to avoid double counting?

**Comment by emtwo** [comment]
Thanks for these updates! 

> Do you think it's prudent to also merge the bucket counts and probe counts queries here to avoid double counting?

I don't think merging bucket counts and probe counts is necessary, just the data cubing by client should be sufficient to address the double counting.

I do want to point out this issue: https://github.com/mozilla/bigquery-etl/issues/987
in which I describe why I'm thinking about bringing back `clients_histogram_bucket_counts_v1`.

This PR and #912 are on my radar for the week.

**Comment by acmiyaguchi** [comment]
Thanks, issue #987 makes sense after reviewing the related PR. I'll keep it in mind as I work through this.

**Comment by emtwo** [comment]
After taking a closer look here, I think I may have misunderstood your question earlier. In order to address the double counting issue, we need to apply the data cubing/static combos per `client_id`. That way, if a client has several rows with different `app_build_id`, they are counted only once when we group over all build ids. In this PR, the static combos would have still been applied after `client_id` was excluded in the grouping in `clients_histogram_bucket_counts`, right?

**Comment by acmiyaguchi** [comment]
> After taking a closer look here, I think I may have misunderstood your question earlier. In order to address the double counting issue, we need to apply the data cubing/static combos per `client_id`. That way, if a client has several rows with different `app_build_id`, they are counted only once when we group over all build ids. In this PR, the static combos would have still been applied after `client_id` was excluded in the grouping in `clients_histogram_bucket_counts`, right?

Yes, this actually doesn't handle double counting of any kind. I've added #998 to add client_id as an attribute to cube over in bucket counts. This also changes the name of the bucket count tables to include the `clients_` prefix, since it now does include client ids again.

**Comment by emtwo** [comment]
> Yes, this actually doesn't handle double counting of any kind. I've added #998 to add client_id as an attribute to cube over in bucket counts. This also changes the name of the bucket count tables to include the `clients_` prefix, since it now does include client ids again.

Got it, ok great. I look this over again tomorrow as well as #998. Thanks!

**Comment by acmiyaguchi** [comment]
Closed in favor of #1002

**Pull request closed without merging**
