### PR TITLE
Update marketing_attributable_metrics to match dashboard

### PR DESCRIPTION
**Pull request by bani**
This updated marketing_attributable_metrics to match the data in the current dashboard.
Main changes are using the country from first seen table and doing an outer join for search.

Checklist for reviewer:

- [ ] Commits should reference a bug or github issue, if relevant (if a bug is referenced, the pull request should include the bug number in the title)
- [ ] If the PR comes from a fork, trigger integration CI tests by running the [Push to upstream workflow](https://github.com/mozilla/bigquery-etl/actions/workflows/push-to-upstream.yml) and provide the `<username>:<branch>` of the fork as parameter. The parameter will also show up
in the logs of the `manual-trigger-required-for-fork` CI task together with more detailed instructions.
- [ ] If adding a new field to a query, ensure that the schema and dependent downstream schemas have been updated

For modifications to schemas in restricted namespaces (see [`CODEOWNERS`](/CODEOWNERS)):
- [ ] Follow the [change control procedure](https://docs.google.com/document/d/1TTJi4ht7NuzX6BPG_KTr6omaZg70cEpxe9xlpfnHj9k/edit#heading=h.ttegrcfy18ck)

### CODE REVIEW

**Comment by skahmann3** [comment]
Not sure if this PR is meant to be the final stage dataset for marketing analyses or if that's another PR, but it would be good to incorporate some of the changes from [Xuan's analysis](https://colab.research.google.com/drive/1JlOwWRx_HzEtjyeBqls7UKf8L2d6Bdya#scrollTo=UfydwRaYX4dy). She has indicators for new, single day, and multiday profiles which would be useful when setting up future monitoring analyses

**Comment by bani** [comment]
@skahmann3 makes sense! I'd like to merge this version so that we can have the correct numbers on the new Looker explore, but we can iterate on it based on feedback!

**Comment by bani** [comment]
I think the main issue regarding single day / multi day is that we shouldn't report on that for clients that are too new, and usually Marketing wants the full month results right after the month ends. Maybe we could add a "TBD" category.

**Review by skahmann3 — APPROVED** [review]
Approving these changes. Though as a note for dashboard development, we need "average clicks per retained multiday client." This will require merging on an aggregated dataset which identifies the single day clients so they can be removed. This can be easily done in Looker and redash

**Pull request merged**
