### PR TITLE
Public GLAM datasets

### PR DESCRIPTION
**Pull request by scholtzan**
This is for publishing GLAM aggregates data. The related data review bug is here: https://bugzilla.mozilla.org/show_bug.cgi?id=1866889

Checklist for reviewer:

- [ ] Commits should reference a bug or github issue, if relevant (if a bug is referenced, the pull request should include the bug number in the title).
- [ ] If the PR comes from a fork, trigger integration CI tests by running the [Push to upstream workflow](https://github.com/mozilla/bigquery-etl/actions/workflows/push-to-upstream.yml) and provide the `<username>:<branch>` of the fork as parameter. The parameter will also show up
in the logs of the `manual-trigger-required-for-fork` CI task together with more detailed instructions.
- [ ] If adding a new field to a query, ensure that the schema and dependent downstream schemas have been updated.
- [ ] When adding a new derived dataset, ensure that data is not available already (fully or partially) and recommend extending an existing dataset in favor of creating new ones. Data can be available in the [bigquery-etl repository](https://github.com/mozilla/bigquery-etl), [looker-hub](https://github.com/mozilla/looker-hub) or in [looker-spoke-default](https://github.com/mozilla/looker-spoke-default/tree/e1315853507fc1ac6e78d252d53dc8df5f5f322b).

For modifications to schemas in restricted namespaces (see [`CODEOWNERS`](https://github.com/mozilla/bigquery-etl/blob/main/CODEOWNERS)):
- [ ] Follow the [change control procedure](https://docs.google.com/document/d/1TTJi4ht7NuzX6BPG_KTr6omaZg70cEpxe9xlpfnHj9k/edit#heading=h.ttegrcfy18ck)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2040)

### CODE REVIEW

**Comment by edugfilho** [comment]
I found some extra probes that are apparently getting skipped during process on TMO:
- [MESSAGE_MANAGER_MESSAGE_SIZE, VIDEO_DETAILED_DROPPED_FRAMES_PROPORTION](https://github.com/mozilla/python_mozaggregator/blob/6c0119bfd0b535346c37cb3f707d998039d3e24b/mozaggregator/aggregator.py#L130)
- [browser.engagement.navigation](https://github.com/mozilla/python_mozaggregator/blob/6c0119bfd0b535346c37cb3f707d998039d3e24b/mozaggregator/aggregator.py#L239C29-L239C58)

**Review by rafrombrc — CHANGES_REQUESTED** [review]
Following up on our discussion in a meeting, to ensure we don't inadvertently publish anything that shouldn't be public we'll want to omit the Fenix data and filter out the additional fields that Eduardo found the aggregates processing job to be excluding elsewhere in the codebase. Once that's done you've got a green light from me. :+1:

**Comment by scholtzan** [comment]
Removed Fenix and added additional filters based on the mozaggregator source code

**Comment by scholtzan** [comment]
Rob gave his r+ on Slack, so let's get this merged

**Pull request merged**
