### PR TITLE
Bug 1731093 - Generate events_daily for other Fenix variants

### PR DESCRIPTION
**Pull request by wlach**
In particular, Firefox for Android beta and nightly channels.

### CODE REVIEW

**Comment by wlach** [comment]
Hmm, looking more closely-- I don't think this initial approach is going to work: for a cross app dataset, we need a uniform event type mappings across channels. Back to the drawing board.

**Comment by wlach** [comment]
Bah, there's still some issues with the tests that need to be resolved before we can merge this.

**Comment by wlach** [comment]
This also cleans up and improves some very minor things while I was here. I believe the dry run and tests are only failing because we have not yet backfilled the tables in.

**Comment by akkomar** [comment]
> This also cleans up and improves some very minor things while I was here. I believe the dry run and tests are only failing because we have not yet backfilled the tables in.

Yes, looks like some tests are failing because fenix_derived.events_daily_v1 is not yet created.

**Review by akkomar — APPROVED** [review]

**Comment by wlach** [comment]
I've created `fenix_derived.events_types_history_v1` and `fenix_derived.events_types_v1`, backfilled up to yesterday and `fenix_derived.events_daily_v1` backfilled only on `2020-01-01` (the first day we started collecting data for this dataset).

I'll merge this PR and backfill the rest on Monday.

**Pull request merged**
