### PR TITLE
bug 1792965 - Use the established normalized_channel in events_unnested for single-dataset apps

### PR DESCRIPTION
**Pull request by chutten**
If there isn't a separate app_id per channel, we'll get "release" overriding the already-correct-and-normalized `normalized_channel` from the source table.

Checklist for reviewer:

- [x] Commits should reference a bug or github issue, if relevant (if a bug is referenced, the pull request should include the bug number in the title)
- [ ] If the PR comes from a fork, trigger integration CI tests by running the [Push to upstream workflow](https://github.com/mozilla/bigquery-etl/actions/workflows/push-to-upstream.yml) and provide the `<username>:<branch>` of the fork as parameter. The parameter will also show up
in the logs of the `manual-trigger-required-for-fork` CI task together with more detailed instructions.
- [n/a] If adding a new field to a query, ensure that the schema and dependent downstream schemas have been updated

For modifications to schemas in restricted namespaces (see [`CODEOWNERS`](/CODEOWNERS)):
- [n/a] Follow the [change control procedure](https://docs.google.com/document/d/1TTJi4ht7NuzX6BPG_KTr6omaZg70cEpxe9xlpfnHj9k/edit#heading=h.ttegrcfy18ck)

### CODE REVIEW

**Comment by chutten** [comment]
I might need some help figuring out what's up with `test_run_query` and `test_run_query_public_project`

**Comment by chutten** [comment]
(and with how to best write a test)

**Comment by akkomar** [comment]
> I might need some help figuring out what's up with `test_run_query` and `test_run_query_public_project`

These tests were passing on the `trigger-integration` branch but for some reason it wasn't reflected here. Updating this branch with latest changes from `main` and pushing to upstream integration test branch fixed that.

**Review by akkomar — APPROVED** [review]
> (and with how to best write a test)

It looks like we don't yet have tests for these autogenerated queries. I validated this by generating `events_unnested` views and manually querying `fenix` and `firefox_desktop` ones (see this [query](https://sql.telemetry.mozilla.org/queries/87995/source) for desktop view that is affected by this change). Both views look good so I think we can go ahead and merge this.

**Comment by chutten** [comment]
(does that mean I get to update the branch and push the button, or should someone else make the merge happen?)

**Comment by chutten** [comment]
Thanks, @akkomar ! 

...do we wanna backfill these columns at all? Or, since these are views, will they "Just Work"(tm)?

**Comment by akkomar** [comment]
> Thanks, @akkomar !
> 
> ...do we wanna backfill these columns at all? Or, since these are views, will they "Just Work"(tm)?

Correct, since these are views and they have already been deployed this just works.

**Pull request merged**
